// Code generated by ent, DO NOT EDIT.

package syllabi

import (
	"hexagonal-go-backend/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldEQ(FieldUpdatedAt, v))
}

// VersionID applies equality check predicate on the "version_id" field. It's identical to VersionIDEQ.
func VersionID(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldEQ(FieldVersionID, v))
}

// Objectives applies equality check predicate on the "objectives" field. It's identical to ObjectivesEQ.
func Objectives(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldEQ(FieldObjectives, v))
}

// EntryProfile applies equality check predicate on the "entry_profile" field. It's identical to EntryProfileEQ.
func EntryProfile(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldEQ(FieldEntryProfile, v))
}

// ExitProfile applies equality check predicate on the "exit_profile" field. It's identical to ExitProfileEQ.
func ExitProfile(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldEQ(FieldExitProfile, v))
}

// Methodology applies equality check predicate on the "methodology" field. It's identical to MethodologyEQ.
func Methodology(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldEQ(FieldMethodology, v))
}

// DurationsHours applies equality check predicate on the "durations_hours" field. It's identical to DurationsHoursEQ.
func DurationsHours(v int) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldEQ(FieldDurationsHours, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldLTE(FieldUpdatedAt, v))
}

// VersionIDEQ applies the EQ predicate on the "version_id" field.
func VersionIDEQ(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldEQ(FieldVersionID, v))
}

// VersionIDNEQ applies the NEQ predicate on the "version_id" field.
func VersionIDNEQ(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldNEQ(FieldVersionID, v))
}

// VersionIDIn applies the In predicate on the "version_id" field.
func VersionIDIn(vs ...string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldIn(FieldVersionID, vs...))
}

// VersionIDNotIn applies the NotIn predicate on the "version_id" field.
func VersionIDNotIn(vs ...string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldNotIn(FieldVersionID, vs...))
}

// VersionIDGT applies the GT predicate on the "version_id" field.
func VersionIDGT(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldGT(FieldVersionID, v))
}

// VersionIDGTE applies the GTE predicate on the "version_id" field.
func VersionIDGTE(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldGTE(FieldVersionID, v))
}

// VersionIDLT applies the LT predicate on the "version_id" field.
func VersionIDLT(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldLT(FieldVersionID, v))
}

// VersionIDLTE applies the LTE predicate on the "version_id" field.
func VersionIDLTE(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldLTE(FieldVersionID, v))
}

// VersionIDContains applies the Contains predicate on the "version_id" field.
func VersionIDContains(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldContains(FieldVersionID, v))
}

// VersionIDHasPrefix applies the HasPrefix predicate on the "version_id" field.
func VersionIDHasPrefix(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldHasPrefix(FieldVersionID, v))
}

// VersionIDHasSuffix applies the HasSuffix predicate on the "version_id" field.
func VersionIDHasSuffix(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldHasSuffix(FieldVersionID, v))
}

// VersionIDEqualFold applies the EqualFold predicate on the "version_id" field.
func VersionIDEqualFold(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldEqualFold(FieldVersionID, v))
}

// VersionIDContainsFold applies the ContainsFold predicate on the "version_id" field.
func VersionIDContainsFold(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldContainsFold(FieldVersionID, v))
}

// ObjectivesEQ applies the EQ predicate on the "objectives" field.
func ObjectivesEQ(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldEQ(FieldObjectives, v))
}

// ObjectivesNEQ applies the NEQ predicate on the "objectives" field.
func ObjectivesNEQ(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldNEQ(FieldObjectives, v))
}

// ObjectivesIn applies the In predicate on the "objectives" field.
func ObjectivesIn(vs ...string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldIn(FieldObjectives, vs...))
}

// ObjectivesNotIn applies the NotIn predicate on the "objectives" field.
func ObjectivesNotIn(vs ...string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldNotIn(FieldObjectives, vs...))
}

// ObjectivesGT applies the GT predicate on the "objectives" field.
func ObjectivesGT(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldGT(FieldObjectives, v))
}

// ObjectivesGTE applies the GTE predicate on the "objectives" field.
func ObjectivesGTE(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldGTE(FieldObjectives, v))
}

// ObjectivesLT applies the LT predicate on the "objectives" field.
func ObjectivesLT(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldLT(FieldObjectives, v))
}

// ObjectivesLTE applies the LTE predicate on the "objectives" field.
func ObjectivesLTE(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldLTE(FieldObjectives, v))
}

// ObjectivesContains applies the Contains predicate on the "objectives" field.
func ObjectivesContains(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldContains(FieldObjectives, v))
}

// ObjectivesHasPrefix applies the HasPrefix predicate on the "objectives" field.
func ObjectivesHasPrefix(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldHasPrefix(FieldObjectives, v))
}

// ObjectivesHasSuffix applies the HasSuffix predicate on the "objectives" field.
func ObjectivesHasSuffix(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldHasSuffix(FieldObjectives, v))
}

// ObjectivesIsNil applies the IsNil predicate on the "objectives" field.
func ObjectivesIsNil() predicate.Syllabi {
	return predicate.Syllabi(sql.FieldIsNull(FieldObjectives))
}

// ObjectivesNotNil applies the NotNil predicate on the "objectives" field.
func ObjectivesNotNil() predicate.Syllabi {
	return predicate.Syllabi(sql.FieldNotNull(FieldObjectives))
}

// ObjectivesEqualFold applies the EqualFold predicate on the "objectives" field.
func ObjectivesEqualFold(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldEqualFold(FieldObjectives, v))
}

// ObjectivesContainsFold applies the ContainsFold predicate on the "objectives" field.
func ObjectivesContainsFold(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldContainsFold(FieldObjectives, v))
}

// EntryProfileEQ applies the EQ predicate on the "entry_profile" field.
func EntryProfileEQ(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldEQ(FieldEntryProfile, v))
}

// EntryProfileNEQ applies the NEQ predicate on the "entry_profile" field.
func EntryProfileNEQ(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldNEQ(FieldEntryProfile, v))
}

// EntryProfileIn applies the In predicate on the "entry_profile" field.
func EntryProfileIn(vs ...string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldIn(FieldEntryProfile, vs...))
}

// EntryProfileNotIn applies the NotIn predicate on the "entry_profile" field.
func EntryProfileNotIn(vs ...string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldNotIn(FieldEntryProfile, vs...))
}

// EntryProfileGT applies the GT predicate on the "entry_profile" field.
func EntryProfileGT(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldGT(FieldEntryProfile, v))
}

// EntryProfileGTE applies the GTE predicate on the "entry_profile" field.
func EntryProfileGTE(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldGTE(FieldEntryProfile, v))
}

// EntryProfileLT applies the LT predicate on the "entry_profile" field.
func EntryProfileLT(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldLT(FieldEntryProfile, v))
}

// EntryProfileLTE applies the LTE predicate on the "entry_profile" field.
func EntryProfileLTE(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldLTE(FieldEntryProfile, v))
}

// EntryProfileContains applies the Contains predicate on the "entry_profile" field.
func EntryProfileContains(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldContains(FieldEntryProfile, v))
}

// EntryProfileHasPrefix applies the HasPrefix predicate on the "entry_profile" field.
func EntryProfileHasPrefix(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldHasPrefix(FieldEntryProfile, v))
}

// EntryProfileHasSuffix applies the HasSuffix predicate on the "entry_profile" field.
func EntryProfileHasSuffix(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldHasSuffix(FieldEntryProfile, v))
}

// EntryProfileIsNil applies the IsNil predicate on the "entry_profile" field.
func EntryProfileIsNil() predicate.Syllabi {
	return predicate.Syllabi(sql.FieldIsNull(FieldEntryProfile))
}

// EntryProfileNotNil applies the NotNil predicate on the "entry_profile" field.
func EntryProfileNotNil() predicate.Syllabi {
	return predicate.Syllabi(sql.FieldNotNull(FieldEntryProfile))
}

// EntryProfileEqualFold applies the EqualFold predicate on the "entry_profile" field.
func EntryProfileEqualFold(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldEqualFold(FieldEntryProfile, v))
}

// EntryProfileContainsFold applies the ContainsFold predicate on the "entry_profile" field.
func EntryProfileContainsFold(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldContainsFold(FieldEntryProfile, v))
}

// ExitProfileEQ applies the EQ predicate on the "exit_profile" field.
func ExitProfileEQ(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldEQ(FieldExitProfile, v))
}

// ExitProfileNEQ applies the NEQ predicate on the "exit_profile" field.
func ExitProfileNEQ(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldNEQ(FieldExitProfile, v))
}

// ExitProfileIn applies the In predicate on the "exit_profile" field.
func ExitProfileIn(vs ...string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldIn(FieldExitProfile, vs...))
}

// ExitProfileNotIn applies the NotIn predicate on the "exit_profile" field.
func ExitProfileNotIn(vs ...string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldNotIn(FieldExitProfile, vs...))
}

// ExitProfileGT applies the GT predicate on the "exit_profile" field.
func ExitProfileGT(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldGT(FieldExitProfile, v))
}

// ExitProfileGTE applies the GTE predicate on the "exit_profile" field.
func ExitProfileGTE(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldGTE(FieldExitProfile, v))
}

// ExitProfileLT applies the LT predicate on the "exit_profile" field.
func ExitProfileLT(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldLT(FieldExitProfile, v))
}

// ExitProfileLTE applies the LTE predicate on the "exit_profile" field.
func ExitProfileLTE(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldLTE(FieldExitProfile, v))
}

// ExitProfileContains applies the Contains predicate on the "exit_profile" field.
func ExitProfileContains(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldContains(FieldExitProfile, v))
}

// ExitProfileHasPrefix applies the HasPrefix predicate on the "exit_profile" field.
func ExitProfileHasPrefix(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldHasPrefix(FieldExitProfile, v))
}

// ExitProfileHasSuffix applies the HasSuffix predicate on the "exit_profile" field.
func ExitProfileHasSuffix(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldHasSuffix(FieldExitProfile, v))
}

// ExitProfileIsNil applies the IsNil predicate on the "exit_profile" field.
func ExitProfileIsNil() predicate.Syllabi {
	return predicate.Syllabi(sql.FieldIsNull(FieldExitProfile))
}

// ExitProfileNotNil applies the NotNil predicate on the "exit_profile" field.
func ExitProfileNotNil() predicate.Syllabi {
	return predicate.Syllabi(sql.FieldNotNull(FieldExitProfile))
}

// ExitProfileEqualFold applies the EqualFold predicate on the "exit_profile" field.
func ExitProfileEqualFold(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldEqualFold(FieldExitProfile, v))
}

// ExitProfileContainsFold applies the ContainsFold predicate on the "exit_profile" field.
func ExitProfileContainsFold(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldContainsFold(FieldExitProfile, v))
}

// MethodologyEQ applies the EQ predicate on the "methodology" field.
func MethodologyEQ(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldEQ(FieldMethodology, v))
}

// MethodologyNEQ applies the NEQ predicate on the "methodology" field.
func MethodologyNEQ(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldNEQ(FieldMethodology, v))
}

// MethodologyIn applies the In predicate on the "methodology" field.
func MethodologyIn(vs ...string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldIn(FieldMethodology, vs...))
}

// MethodologyNotIn applies the NotIn predicate on the "methodology" field.
func MethodologyNotIn(vs ...string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldNotIn(FieldMethodology, vs...))
}

// MethodologyGT applies the GT predicate on the "methodology" field.
func MethodologyGT(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldGT(FieldMethodology, v))
}

// MethodologyGTE applies the GTE predicate on the "methodology" field.
func MethodologyGTE(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldGTE(FieldMethodology, v))
}

// MethodologyLT applies the LT predicate on the "methodology" field.
func MethodologyLT(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldLT(FieldMethodology, v))
}

// MethodologyLTE applies the LTE predicate on the "methodology" field.
func MethodologyLTE(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldLTE(FieldMethodology, v))
}

// MethodologyContains applies the Contains predicate on the "methodology" field.
func MethodologyContains(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldContains(FieldMethodology, v))
}

// MethodologyHasPrefix applies the HasPrefix predicate on the "methodology" field.
func MethodologyHasPrefix(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldHasPrefix(FieldMethodology, v))
}

// MethodologyHasSuffix applies the HasSuffix predicate on the "methodology" field.
func MethodologyHasSuffix(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldHasSuffix(FieldMethodology, v))
}

// MethodologyIsNil applies the IsNil predicate on the "methodology" field.
func MethodologyIsNil() predicate.Syllabi {
	return predicate.Syllabi(sql.FieldIsNull(FieldMethodology))
}

// MethodologyNotNil applies the NotNil predicate on the "methodology" field.
func MethodologyNotNil() predicate.Syllabi {
	return predicate.Syllabi(sql.FieldNotNull(FieldMethodology))
}

// MethodologyEqualFold applies the EqualFold predicate on the "methodology" field.
func MethodologyEqualFold(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldEqualFold(FieldMethodology, v))
}

// MethodologyContainsFold applies the ContainsFold predicate on the "methodology" field.
func MethodologyContainsFold(v string) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldContainsFold(FieldMethodology, v))
}

// DurationsHoursEQ applies the EQ predicate on the "durations_hours" field.
func DurationsHoursEQ(v int) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldEQ(FieldDurationsHours, v))
}

// DurationsHoursNEQ applies the NEQ predicate on the "durations_hours" field.
func DurationsHoursNEQ(v int) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldNEQ(FieldDurationsHours, v))
}

// DurationsHoursIn applies the In predicate on the "durations_hours" field.
func DurationsHoursIn(vs ...int) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldIn(FieldDurationsHours, vs...))
}

// DurationsHoursNotIn applies the NotIn predicate on the "durations_hours" field.
func DurationsHoursNotIn(vs ...int) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldNotIn(FieldDurationsHours, vs...))
}

// DurationsHoursGT applies the GT predicate on the "durations_hours" field.
func DurationsHoursGT(v int) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldGT(FieldDurationsHours, v))
}

// DurationsHoursGTE applies the GTE predicate on the "durations_hours" field.
func DurationsHoursGTE(v int) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldGTE(FieldDurationsHours, v))
}

// DurationsHoursLT applies the LT predicate on the "durations_hours" field.
func DurationsHoursLT(v int) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldLT(FieldDurationsHours, v))
}

// DurationsHoursLTE applies the LTE predicate on the "durations_hours" field.
func DurationsHoursLTE(v int) predicate.Syllabi {
	return predicate.Syllabi(sql.FieldLTE(FieldDurationsHours, v))
}

// HasVersion applies the HasEdge predicate on the "version" edge.
func HasVersion() predicate.Syllabi {
	return predicate.Syllabi(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, VersionTable, VersionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVersionWith applies the HasEdge predicate on the "version" edge with a given conditions (other predicates).
func HasVersionWith(preds ...predicate.CourseVersions) predicate.Syllabi {
	return predicate.Syllabi(func(s *sql.Selector) {
		step := newVersionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Syllabi) predicate.Syllabi {
	return predicate.Syllabi(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Syllabi) predicate.Syllabi {
	return predicate.Syllabi(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Syllabi) predicate.Syllabi {
	return predicate.Syllabi(sql.NotPredicates(p))
}
