// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hexagonal-go-backend/internal/ent/activities"
	"hexagonal-go-backend/internal/ent/courseresources"
	"hexagonal-go-backend/internal/ent/lessons"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ActivitiesCreate is the builder for creating a Activities entity.
type ActivitiesCreate struct {
	config
	mutation *ActivitiesMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ActivitiesCreate) SetCreatedAt(v time.Time) *ActivitiesCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ActivitiesCreate) SetNillableCreatedAt(v *time.Time) *ActivitiesCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ActivitiesCreate) SetUpdatedAt(v time.Time) *ActivitiesCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ActivitiesCreate) SetNillableUpdatedAt(v *time.Time) *ActivitiesCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetLessonID sets the "lesson_id" field.
func (_c *ActivitiesCreate) SetLessonID(v string) *ActivitiesCreate {
	_c.mutation.SetLessonID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *ActivitiesCreate) SetTitle(v string) *ActivitiesCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetType sets the "type" field.
func (_c *ActivitiesCreate) SetType(v string) *ActivitiesCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetIsRequired sets the "is_required" field.
func (_c *ActivitiesCreate) SetIsRequired(v bool) *ActivitiesCreate {
	_c.mutation.SetIsRequired(v)
	return _c
}

// SetNillableIsRequired sets the "is_required" field if the given value is not nil.
func (_c *ActivitiesCreate) SetNillableIsRequired(v *bool) *ActivitiesCreate {
	if v != nil {
		_c.SetIsRequired(*v)
	}
	return _c
}

// SetSequenceOrder sets the "sequence_order" field.
func (_c *ActivitiesCreate) SetSequenceOrder(v int) *ActivitiesCreate {
	_c.mutation.SetSequenceOrder(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ActivitiesCreate) SetID(v string) *ActivitiesCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ActivitiesCreate) SetNillableID(v *string) *ActivitiesCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetLesson sets the "lesson" edge to the Lessons entity.
func (_c *ActivitiesCreate) SetLesson(v *Lessons) *ActivitiesCreate {
	return _c.SetLessonID(v.ID)
}

// AddResourceIDs adds the "resources" edge to the CourseResources entity by IDs.
func (_c *ActivitiesCreate) AddResourceIDs(ids ...string) *ActivitiesCreate {
	_c.mutation.AddResourceIDs(ids...)
	return _c
}

// AddResources adds the "resources" edges to the CourseResources entity.
func (_c *ActivitiesCreate) AddResources(v ...*CourseResources) *ActivitiesCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddResourceIDs(ids...)
}

// Mutation returns the ActivitiesMutation object of the builder.
func (_c *ActivitiesCreate) Mutation() *ActivitiesMutation {
	return _c.mutation
}

// Save creates the Activities in the database.
func (_c *ActivitiesCreate) Save(ctx context.Context) (*Activities, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ActivitiesCreate) SaveX(ctx context.Context) *Activities {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ActivitiesCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ActivitiesCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ActivitiesCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := activities.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := activities.DefaultUpdatedAt
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.IsRequired(); !ok {
		v := activities.DefaultIsRequired
		_c.mutation.SetIsRequired(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := activities.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ActivitiesCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Activities.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Activities.updated_at"`)}
	}
	if _, ok := _c.mutation.LessonID(); !ok {
		return &ValidationError{Name: "lesson_id", err: errors.New(`ent: missing required field "Activities.lesson_id"`)}
	}
	if v, ok := _c.mutation.LessonID(); ok {
		if err := activities.LessonIDValidator(v); err != nil {
			return &ValidationError{Name: "lesson_id", err: fmt.Errorf(`ent: validator failed for field "Activities.lesson_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Activities.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := activities.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Activities.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Activities.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := activities.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Activities.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsRequired(); !ok {
		return &ValidationError{Name: "is_required", err: errors.New(`ent: missing required field "Activities.is_required"`)}
	}
	if _, ok := _c.mutation.SequenceOrder(); !ok {
		return &ValidationError{Name: "sequence_order", err: errors.New(`ent: missing required field "Activities.sequence_order"`)}
	}
	if v, ok := _c.mutation.SequenceOrder(); ok {
		if err := activities.SequenceOrderValidator(v); err != nil {
			return &ValidationError{Name: "sequence_order", err: fmt.Errorf(`ent: validator failed for field "Activities.sequence_order": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := activities.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Activities.id": %w`, err)}
		}
	}
	if len(_c.mutation.LessonIDs()) == 0 {
		return &ValidationError{Name: "lesson", err: errors.New(`ent: missing required edge "Activities.lesson"`)}
	}
	return nil
}

func (_c *ActivitiesCreate) sqlSave(ctx context.Context) (*Activities, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Activities.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ActivitiesCreate) createSpec() (*Activities, *sqlgraph.CreateSpec) {
	var (
		_node = &Activities{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(activities.Table, sqlgraph.NewFieldSpec(activities.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(activities.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(activities.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(activities.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(activities.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.IsRequired(); ok {
		_spec.SetField(activities.FieldIsRequired, field.TypeBool, value)
		_node.IsRequired = value
	}
	if value, ok := _c.mutation.SequenceOrder(); ok {
		_spec.SetField(activities.FieldSequenceOrder, field.TypeInt, value)
		_node.SequenceOrder = value
	}
	if nodes := _c.mutation.LessonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activities.LessonTable,
			Columns: []string{activities.LessonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessons.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.LessonID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ResourcesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activities.ResourcesTable,
			Columns: []string{activities.ResourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(courseresources.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ActivitiesCreateBulk is the builder for creating many Activities entities in bulk.
type ActivitiesCreateBulk struct {
	config
	err      error
	builders []*ActivitiesCreate
}

// Save creates the Activities entities in the database.
func (_c *ActivitiesCreateBulk) Save(ctx context.Context) ([]*Activities, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Activities, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ActivitiesMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ActivitiesCreateBulk) SaveX(ctx context.Context) []*Activities {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ActivitiesCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ActivitiesCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
