// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hexagonal-go-backend/internal/ent/coursetemplates"
	"hexagonal-go-backend/internal/ent/courseversions"
	"hexagonal-go-backend/internal/ent/syllabi"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CourseVersionsCreate is the builder for creating a CourseVersions entity.
type CourseVersionsCreate struct {
	config
	mutation *CourseVersionsMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *CourseVersionsCreate) SetCreatedAt(v time.Time) *CourseVersionsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CourseVersionsCreate) SetNillableCreatedAt(v *time.Time) *CourseVersionsCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CourseVersionsCreate) SetUpdatedAt(v time.Time) *CourseVersionsCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CourseVersionsCreate) SetNillableUpdatedAt(v *time.Time) *CourseVersionsCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTemplateID sets the "template_id" field.
func (_c *CourseVersionsCreate) SetTemplateID(v string) *CourseVersionsCreate {
	_c.mutation.SetTemplateID(v)
	return _c
}

// SetVersionTag sets the "version_tag" field.
func (_c *CourseVersionsCreate) SetVersionTag(v string) *CourseVersionsCreate {
	_c.mutation.SetVersionTag(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *CourseVersionsCreate) SetStatus(v string) *CourseVersionsCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetEstimatedHours sets the "estimated_hours" field.
func (_c *CourseVersionsCreate) SetEstimatedHours(v int) *CourseVersionsCreate {
	_c.mutation.SetEstimatedHours(v)
	return _c
}

// SetNillableEstimatedHours sets the "estimated_hours" field if the given value is not nil.
func (_c *CourseVersionsCreate) SetNillableEstimatedHours(v *int) *CourseVersionsCreate {
	if v != nil {
		_c.SetEstimatedHours(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CourseVersionsCreate) SetID(v string) *CourseVersionsCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CourseVersionsCreate) SetNillableID(v *string) *CourseVersionsCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetTemplate sets the "template" edge to the CourseTemplates entity.
func (_c *CourseVersionsCreate) SetTemplate(v *CourseTemplates) *CourseVersionsCreate {
	return _c.SetTemplateID(v.ID)
}

// AddSyllabiIDs adds the "syllabi" edge to the Syllabi entity by IDs.
func (_c *CourseVersionsCreate) AddSyllabiIDs(ids ...string) *CourseVersionsCreate {
	_c.mutation.AddSyllabiIDs(ids...)
	return _c
}

// AddSyllabi adds the "syllabi" edges to the Syllabi entity.
func (_c *CourseVersionsCreate) AddSyllabi(v ...*Syllabi) *CourseVersionsCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSyllabiIDs(ids...)
}

// Mutation returns the CourseVersionsMutation object of the builder.
func (_c *CourseVersionsCreate) Mutation() *CourseVersionsMutation {
	return _c.mutation
}

// Save creates the CourseVersions in the database.
func (_c *CourseVersionsCreate) Save(ctx context.Context) (*CourseVersions, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CourseVersionsCreate) SaveX(ctx context.Context) *CourseVersions {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CourseVersionsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CourseVersionsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CourseVersionsCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := courseversions.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := courseversions.DefaultUpdatedAt
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.EstimatedHours(); !ok {
		v := courseversions.DefaultEstimatedHours
		_c.mutation.SetEstimatedHours(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := courseversions.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CourseVersionsCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CourseVersions.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CourseVersions.updated_at"`)}
	}
	if _, ok := _c.mutation.TemplateID(); !ok {
		return &ValidationError{Name: "template_id", err: errors.New(`ent: missing required field "CourseVersions.template_id"`)}
	}
	if v, ok := _c.mutation.TemplateID(); ok {
		if err := courseversions.TemplateIDValidator(v); err != nil {
			return &ValidationError{Name: "template_id", err: fmt.Errorf(`ent: validator failed for field "CourseVersions.template_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VersionTag(); !ok {
		return &ValidationError{Name: "version_tag", err: errors.New(`ent: missing required field "CourseVersions.version_tag"`)}
	}
	if v, ok := _c.mutation.VersionTag(); ok {
		if err := courseversions.VersionTagValidator(v); err != nil {
			return &ValidationError{Name: "version_tag", err: fmt.Errorf(`ent: validator failed for field "CourseVersions.version_tag": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CourseVersions.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := courseversions.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CourseVersions.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EstimatedHours(); !ok {
		return &ValidationError{Name: "estimated_hours", err: errors.New(`ent: missing required field "CourseVersions.estimated_hours"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := courseversions.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "CourseVersions.id": %w`, err)}
		}
	}
	if len(_c.mutation.TemplateIDs()) == 0 {
		return &ValidationError{Name: "template", err: errors.New(`ent: missing required edge "CourseVersions.template"`)}
	}
	return nil
}

func (_c *CourseVersionsCreate) sqlSave(ctx context.Context) (*CourseVersions, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected CourseVersions.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CourseVersionsCreate) createSpec() (*CourseVersions, *sqlgraph.CreateSpec) {
	var (
		_node = &CourseVersions{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(courseversions.Table, sqlgraph.NewFieldSpec(courseversions.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(courseversions.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(courseversions.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.VersionTag(); ok {
		_spec.SetField(courseversions.FieldVersionTag, field.TypeString, value)
		_node.VersionTag = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(courseversions.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.EstimatedHours(); ok {
		_spec.SetField(courseversions.FieldEstimatedHours, field.TypeInt, value)
		_node.EstimatedHours = value
	}
	if nodes := _c.mutation.TemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   courseversions.TemplateTable,
			Columns: []string{courseversions.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coursetemplates.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TemplateID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SyllabiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courseversions.SyllabiTable,
			Columns: []string{courseversions.SyllabiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syllabi.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CourseVersionsCreateBulk is the builder for creating many CourseVersions entities in bulk.
type CourseVersionsCreateBulk struct {
	config
	err      error
	builders []*CourseVersionsCreate
}

// Save creates the CourseVersions entities in the database.
func (_c *CourseVersionsCreateBulk) Save(ctx context.Context) ([]*CourseVersions, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CourseVersions, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CourseVersionsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CourseVersionsCreateBulk) SaveX(ctx context.Context) []*CourseVersions {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CourseVersionsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CourseVersionsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
