// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"hexagonal-go-backend/internal/ent/coursetemplates"
	"hexagonal-go-backend/internal/ent/courseversions"
	"hexagonal-go-backend/internal/ent/predicate"
	"hexagonal-go-backend/internal/ent/syllabi"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CourseVersionsQuery is the builder for querying CourseVersions entities.
type CourseVersionsQuery struct {
	config
	ctx          *QueryContext
	order        []courseversions.OrderOption
	inters       []Interceptor
	predicates   []predicate.CourseVersions
	withTemplate *CourseTemplatesQuery
	withSyllabi  *SyllabiQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CourseVersionsQuery builder.
func (_q *CourseVersionsQuery) Where(ps ...predicate.CourseVersions) *CourseVersionsQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CourseVersionsQuery) Limit(limit int) *CourseVersionsQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CourseVersionsQuery) Offset(offset int) *CourseVersionsQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CourseVersionsQuery) Unique(unique bool) *CourseVersionsQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CourseVersionsQuery) Order(o ...courseversions.OrderOption) *CourseVersionsQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryTemplate chains the current query on the "template" edge.
func (_q *CourseVersionsQuery) QueryTemplate() *CourseTemplatesQuery {
	query := (&CourseTemplatesClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(courseversions.Table, courseversions.FieldID, selector),
			sqlgraph.To(coursetemplates.Table, coursetemplates.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, courseversions.TemplateTable, courseversions.TemplateColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySyllabi chains the current query on the "syllabi" edge.
func (_q *CourseVersionsQuery) QuerySyllabi() *SyllabiQuery {
	query := (&SyllabiClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(courseversions.Table, courseversions.FieldID, selector),
			sqlgraph.To(syllabi.Table, syllabi.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, courseversions.SyllabiTable, courseversions.SyllabiColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CourseVersions entity from the query.
// Returns a *NotFoundError when no CourseVersions was found.
func (_q *CourseVersionsQuery) First(ctx context.Context) (*CourseVersions, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{courseversions.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CourseVersionsQuery) FirstX(ctx context.Context) *CourseVersions {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CourseVersions ID from the query.
// Returns a *NotFoundError when no CourseVersions ID was found.
func (_q *CourseVersionsQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{courseversions.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *CourseVersionsQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CourseVersions entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CourseVersions entity is found.
// Returns a *NotFoundError when no CourseVersions entities are found.
func (_q *CourseVersionsQuery) Only(ctx context.Context) (*CourseVersions, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{courseversions.Label}
	default:
		return nil, &NotSingularError{courseversions.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CourseVersionsQuery) OnlyX(ctx context.Context) *CourseVersions {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CourseVersions ID in the query.
// Returns a *NotSingularError when more than one CourseVersions ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *CourseVersionsQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{courseversions.Label}
	default:
		err = &NotSingularError{courseversions.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *CourseVersionsQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CourseVersionsSlice.
func (_q *CourseVersionsQuery) All(ctx context.Context) ([]*CourseVersions, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CourseVersions, *CourseVersionsQuery]()
	return withInterceptors[[]*CourseVersions](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *CourseVersionsQuery) AllX(ctx context.Context) []*CourseVersions {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CourseVersions IDs.
func (_q *CourseVersionsQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(courseversions.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *CourseVersionsQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *CourseVersionsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*CourseVersionsQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CourseVersionsQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CourseVersionsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CourseVersionsQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CourseVersionsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CourseVersionsQuery) Clone() *CourseVersionsQuery {
	if _q == nil {
		return nil
	}
	return &CourseVersionsQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]courseversions.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.CourseVersions{}, _q.predicates...),
		withTemplate: _q.withTemplate.Clone(),
		withSyllabi:  _q.withSyllabi.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithTemplate tells the query-builder to eager-load the nodes that are connected to
// the "template" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CourseVersionsQuery) WithTemplate(opts ...func(*CourseTemplatesQuery)) *CourseVersionsQuery {
	query := (&CourseTemplatesClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTemplate = query
	return _q
}

// WithSyllabi tells the query-builder to eager-load the nodes that are connected to
// the "syllabi" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CourseVersionsQuery) WithSyllabi(opts ...func(*SyllabiQuery)) *CourseVersionsQuery {
	query := (&SyllabiClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSyllabi = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CourseVersions.Query().
//		GroupBy(courseversions.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CourseVersionsQuery) GroupBy(field string, fields ...string) *CourseVersionsGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CourseVersionsGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = courseversions.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.CourseVersions.Query().
//		Select(courseversions.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *CourseVersionsQuery) Select(fields ...string) *CourseVersionsSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &CourseVersionsSelect{CourseVersionsQuery: _q}
	sbuild.label = courseversions.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CourseVersionsSelect configured with the given aggregations.
func (_q *CourseVersionsQuery) Aggregate(fns ...AggregateFunc) *CourseVersionsSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *CourseVersionsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !courseversions.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *CourseVersionsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CourseVersions, error) {
	var (
		nodes       = []*CourseVersions{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withTemplate != nil,
			_q.withSyllabi != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CourseVersions).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CourseVersions{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withTemplate; query != nil {
		if err := _q.loadTemplate(ctx, query, nodes, nil,
			func(n *CourseVersions, e *CourseTemplates) { n.Edges.Template = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSyllabi; query != nil {
		if err := _q.loadSyllabi(ctx, query, nodes,
			func(n *CourseVersions) { n.Edges.Syllabi = []*Syllabi{} },
			func(n *CourseVersions, e *Syllabi) { n.Edges.Syllabi = append(n.Edges.Syllabi, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *CourseVersionsQuery) loadTemplate(ctx context.Context, query *CourseTemplatesQuery, nodes []*CourseVersions, init func(*CourseVersions), assign func(*CourseVersions, *CourseTemplates)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*CourseVersions)
	for i := range nodes {
		fk := nodes[i].TemplateID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(coursetemplates.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "template_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CourseVersionsQuery) loadSyllabi(ctx context.Context, query *SyllabiQuery, nodes []*CourseVersions, init func(*CourseVersions), assign func(*CourseVersions, *Syllabi)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*CourseVersions)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(syllabi.FieldVersionID)
	}
	query.Where(predicate.Syllabi(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(courseversions.SyllabiColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.VersionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "version_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *CourseVersionsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CourseVersionsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(courseversions.Table, courseversions.Columns, sqlgraph.NewFieldSpec(courseversions.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, courseversions.FieldID)
		for i := range fields {
			if fields[i] != courseversions.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withTemplate != nil {
			_spec.Node.AddColumnOnce(courseversions.FieldTemplateID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CourseVersionsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(courseversions.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = courseversions.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CourseVersionsGroupBy is the group-by builder for CourseVersions entities.
type CourseVersionsGroupBy struct {
	selector
	build *CourseVersionsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *CourseVersionsGroupBy) Aggregate(fns ...AggregateFunc) *CourseVersionsGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *CourseVersionsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CourseVersionsQuery, *CourseVersionsGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *CourseVersionsGroupBy) sqlScan(ctx context.Context, root *CourseVersionsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CourseVersionsSelect is the builder for selecting fields of CourseVersions entities.
type CourseVersionsSelect struct {
	*CourseVersionsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *CourseVersionsSelect) Aggregate(fns ...AggregateFunc) *CourseVersionsSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *CourseVersionsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CourseVersionsQuery, *CourseVersionsSelect](ctx, _s.CourseVersionsQuery, _s, _s.inters, v)
}

func (_s *CourseVersionsSelect) sqlScan(ctx context.Context, root *CourseVersionsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
