// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"hexagonal-go-backend/internal/ent/coursemodules"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// CourseModules is the model entity for the CourseModules schema.
type CourseModules struct {
	config
	// ID of the ent.
	ID           string `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CourseModules) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case coursemodules.FieldID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CourseModules fields.
func (_m *CourseModules) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case coursemodules.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CourseModules.
// This includes values selected through modifiers, order, etc.
func (_m *CourseModules) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CourseModules.
// Note that you need to call CourseModules.Unwrap() before calling this method if this CourseModules
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CourseModules) Update() *CourseModulesUpdateOne {
	return NewCourseModulesClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CourseModules entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CourseModules) Unwrap() *CourseModules {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CourseModules is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CourseModules) String() string {
	var builder strings.Builder
	builder.WriteString("CourseModules(")
	builder.WriteString(fmt.Sprintf("id=%v", _m.ID))
	builder.WriteByte(')')
	return builder.String()
}

// CourseModulesSlice is a parsable slice of CourseModules.
type CourseModulesSlice []*CourseModules
