// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hexagonal-go-backend/internal/ent/coursemodules"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CourseModulesCreate is the builder for creating a CourseModules entity.
type CourseModulesCreate struct {
	config
	mutation *CourseModulesMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *CourseModulesCreate) SetCreatedAt(v time.Time) *CourseModulesCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CourseModulesCreate) SetNillableCreatedAt(v *time.Time) *CourseModulesCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CourseModulesCreate) SetUpdatedAt(v time.Time) *CourseModulesCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CourseModulesCreate) SetNillableUpdatedAt(v *time.Time) *CourseModulesCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetVersionID sets the "version_id" field.
func (_c *CourseModulesCreate) SetVersionID(v string) *CourseModulesCreate {
	_c.mutation.SetVersionID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *CourseModulesCreate) SetTitle(v string) *CourseModulesCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetSequenceOrder sets the "sequence_order" field.
func (_c *CourseModulesCreate) SetSequenceOrder(v int) *CourseModulesCreate {
	_c.mutation.SetSequenceOrder(v)
	return _c
}

// SetID sets the "id" field.
func (_c *CourseModulesCreate) SetID(v string) *CourseModulesCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CourseModulesCreate) SetNillableID(v *string) *CourseModulesCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the CourseModulesMutation object of the builder.
func (_c *CourseModulesCreate) Mutation() *CourseModulesMutation {
	return _c.mutation
}

// Save creates the CourseModules in the database.
func (_c *CourseModulesCreate) Save(ctx context.Context) (*CourseModules, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CourseModulesCreate) SaveX(ctx context.Context) *CourseModules {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CourseModulesCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CourseModulesCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CourseModulesCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := coursemodules.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := coursemodules.DefaultUpdatedAt
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := coursemodules.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CourseModulesCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CourseModules.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CourseModules.updated_at"`)}
	}
	if _, ok := _c.mutation.VersionID(); !ok {
		return &ValidationError{Name: "version_id", err: errors.New(`ent: missing required field "CourseModules.version_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "CourseModules.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := coursemodules.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "CourseModules.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SequenceOrder(); !ok {
		return &ValidationError{Name: "sequence_order", err: errors.New(`ent: missing required field "CourseModules.sequence_order"`)}
	}
	if v, ok := _c.mutation.SequenceOrder(); ok {
		if err := coursemodules.SequenceOrderValidator(v); err != nil {
			return &ValidationError{Name: "sequence_order", err: fmt.Errorf(`ent: validator failed for field "CourseModules.sequence_order": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := coursemodules.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "CourseModules.id": %w`, err)}
		}
	}
	return nil
}

func (_c *CourseModulesCreate) sqlSave(ctx context.Context) (*CourseModules, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected CourseModules.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CourseModulesCreate) createSpec() (*CourseModules, *sqlgraph.CreateSpec) {
	var (
		_node = &CourseModules{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(coursemodules.Table, sqlgraph.NewFieldSpec(coursemodules.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(coursemodules.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(coursemodules.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.VersionID(); ok {
		_spec.SetField(coursemodules.FieldVersionID, field.TypeString, value)
		_node.VersionID = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(coursemodules.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.SequenceOrder(); ok {
		_spec.SetField(coursemodules.FieldSequenceOrder, field.TypeInt, value)
		_node.SequenceOrder = value
	}
	return _node, _spec
}

// CourseModulesCreateBulk is the builder for creating many CourseModules entities in bulk.
type CourseModulesCreateBulk struct {
	config
	err      error
	builders []*CourseModulesCreate
}

// Save creates the CourseModules entities in the database.
func (_c *CourseModulesCreateBulk) Save(ctx context.Context) ([]*CourseModules, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CourseModules, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CourseModulesMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CourseModulesCreateBulk) SaveX(ctx context.Context) []*CourseModules {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CourseModulesCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CourseModulesCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
