// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hexagonal-go-backend/internal/ent/coursetemplates"
	"hexagonal-go-backend/internal/ent/courseversions"
	"hexagonal-go-backend/internal/ent/predicate"
	"hexagonal-go-backend/internal/ent/syllabi"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CourseVersionsUpdate is the builder for updating CourseVersions entities.
type CourseVersionsUpdate struct {
	config
	hooks    []Hook
	mutation *CourseVersionsMutation
}

// Where appends a list predicates to the CourseVersionsUpdate builder.
func (_u *CourseVersionsUpdate) Where(ps ...predicate.CourseVersions) *CourseVersionsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CourseVersionsUpdate) SetUpdatedAt(v time.Time) *CourseVersionsUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTemplateID sets the "template_id" field.
func (_u *CourseVersionsUpdate) SetTemplateID(v string) *CourseVersionsUpdate {
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *CourseVersionsUpdate) SetNillableTemplateID(v *string) *CourseVersionsUpdate {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// SetVersionTag sets the "version_tag" field.
func (_u *CourseVersionsUpdate) SetVersionTag(v string) *CourseVersionsUpdate {
	_u.mutation.SetVersionTag(v)
	return _u
}

// SetNillableVersionTag sets the "version_tag" field if the given value is not nil.
func (_u *CourseVersionsUpdate) SetNillableVersionTag(v *string) *CourseVersionsUpdate {
	if v != nil {
		_u.SetVersionTag(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CourseVersionsUpdate) SetStatus(v string) *CourseVersionsUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CourseVersionsUpdate) SetNillableStatus(v *string) *CourseVersionsUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEstimatedHours sets the "estimated_hours" field.
func (_u *CourseVersionsUpdate) SetEstimatedHours(v int) *CourseVersionsUpdate {
	_u.mutation.ResetEstimatedHours()
	_u.mutation.SetEstimatedHours(v)
	return _u
}

// SetNillableEstimatedHours sets the "estimated_hours" field if the given value is not nil.
func (_u *CourseVersionsUpdate) SetNillableEstimatedHours(v *int) *CourseVersionsUpdate {
	if v != nil {
		_u.SetEstimatedHours(*v)
	}
	return _u
}

// AddEstimatedHours adds value to the "estimated_hours" field.
func (_u *CourseVersionsUpdate) AddEstimatedHours(v int) *CourseVersionsUpdate {
	_u.mutation.AddEstimatedHours(v)
	return _u
}

// SetTemplate sets the "template" edge to the CourseTemplates entity.
func (_u *CourseVersionsUpdate) SetTemplate(v *CourseTemplates) *CourseVersionsUpdate {
	return _u.SetTemplateID(v.ID)
}

// AddSyllabiIDs adds the "syllabi" edge to the Syllabi entity by IDs.
func (_u *CourseVersionsUpdate) AddSyllabiIDs(ids ...string) *CourseVersionsUpdate {
	_u.mutation.AddSyllabiIDs(ids...)
	return _u
}

// AddSyllabi adds the "syllabi" edges to the Syllabi entity.
func (_u *CourseVersionsUpdate) AddSyllabi(v ...*Syllabi) *CourseVersionsUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSyllabiIDs(ids...)
}

// Mutation returns the CourseVersionsMutation object of the builder.
func (_u *CourseVersionsUpdate) Mutation() *CourseVersionsMutation {
	return _u.mutation
}

// ClearTemplate clears the "template" edge to the CourseTemplates entity.
func (_u *CourseVersionsUpdate) ClearTemplate() *CourseVersionsUpdate {
	_u.mutation.ClearTemplate()
	return _u
}

// ClearSyllabi clears all "syllabi" edges to the Syllabi entity.
func (_u *CourseVersionsUpdate) ClearSyllabi() *CourseVersionsUpdate {
	_u.mutation.ClearSyllabi()
	return _u
}

// RemoveSyllabiIDs removes the "syllabi" edge to Syllabi entities by IDs.
func (_u *CourseVersionsUpdate) RemoveSyllabiIDs(ids ...string) *CourseVersionsUpdate {
	_u.mutation.RemoveSyllabiIDs(ids...)
	return _u
}

// RemoveSyllabi removes "syllabi" edges to Syllabi entities.
func (_u *CourseVersionsUpdate) RemoveSyllabi(v ...*Syllabi) *CourseVersionsUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSyllabiIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CourseVersionsUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CourseVersionsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CourseVersionsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CourseVersionsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CourseVersionsUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := courseversions.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CourseVersionsUpdate) check() error {
	if v, ok := _u.mutation.TemplateID(); ok {
		if err := courseversions.TemplateIDValidator(v); err != nil {
			return &ValidationError{Name: "template_id", err: fmt.Errorf(`ent: validator failed for field "CourseVersions.template_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VersionTag(); ok {
		if err := courseversions.VersionTagValidator(v); err != nil {
			return &ValidationError{Name: "version_tag", err: fmt.Errorf(`ent: validator failed for field "CourseVersions.version_tag": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := courseversions.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CourseVersions.status": %w`, err)}
		}
	}
	if _u.mutation.TemplateCleared() && len(_u.mutation.TemplateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CourseVersions.template"`)
	}
	return nil
}

func (_u *CourseVersionsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(courseversions.Table, courseversions.Columns, sqlgraph.NewFieldSpec(courseversions.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(courseversions.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.VersionTag(); ok {
		_spec.SetField(courseversions.FieldVersionTag, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(courseversions.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.EstimatedHours(); ok {
		_spec.SetField(courseversions.FieldEstimatedHours, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEstimatedHours(); ok {
		_spec.AddField(courseversions.FieldEstimatedHours, field.TypeInt, value)
	}
	if _u.mutation.TemplateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   courseversions.TemplateTable,
			Columns: []string{courseversions.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coursetemplates.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   courseversions.TemplateTable,
			Columns: []string{courseversions.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coursetemplates.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SyllabiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courseversions.SyllabiTable,
			Columns: []string{courseversions.SyllabiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syllabi.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSyllabiIDs(); len(nodes) > 0 && !_u.mutation.SyllabiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courseversions.SyllabiTable,
			Columns: []string{courseversions.SyllabiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syllabi.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SyllabiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courseversions.SyllabiTable,
			Columns: []string{courseversions.SyllabiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syllabi.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{courseversions.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CourseVersionsUpdateOne is the builder for updating a single CourseVersions entity.
type CourseVersionsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CourseVersionsMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CourseVersionsUpdateOne) SetUpdatedAt(v time.Time) *CourseVersionsUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTemplateID sets the "template_id" field.
func (_u *CourseVersionsUpdateOne) SetTemplateID(v string) *CourseVersionsUpdateOne {
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *CourseVersionsUpdateOne) SetNillableTemplateID(v *string) *CourseVersionsUpdateOne {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// SetVersionTag sets the "version_tag" field.
func (_u *CourseVersionsUpdateOne) SetVersionTag(v string) *CourseVersionsUpdateOne {
	_u.mutation.SetVersionTag(v)
	return _u
}

// SetNillableVersionTag sets the "version_tag" field if the given value is not nil.
func (_u *CourseVersionsUpdateOne) SetNillableVersionTag(v *string) *CourseVersionsUpdateOne {
	if v != nil {
		_u.SetVersionTag(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CourseVersionsUpdateOne) SetStatus(v string) *CourseVersionsUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CourseVersionsUpdateOne) SetNillableStatus(v *string) *CourseVersionsUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEstimatedHours sets the "estimated_hours" field.
func (_u *CourseVersionsUpdateOne) SetEstimatedHours(v int) *CourseVersionsUpdateOne {
	_u.mutation.ResetEstimatedHours()
	_u.mutation.SetEstimatedHours(v)
	return _u
}

// SetNillableEstimatedHours sets the "estimated_hours" field if the given value is not nil.
func (_u *CourseVersionsUpdateOne) SetNillableEstimatedHours(v *int) *CourseVersionsUpdateOne {
	if v != nil {
		_u.SetEstimatedHours(*v)
	}
	return _u
}

// AddEstimatedHours adds value to the "estimated_hours" field.
func (_u *CourseVersionsUpdateOne) AddEstimatedHours(v int) *CourseVersionsUpdateOne {
	_u.mutation.AddEstimatedHours(v)
	return _u
}

// SetTemplate sets the "template" edge to the CourseTemplates entity.
func (_u *CourseVersionsUpdateOne) SetTemplate(v *CourseTemplates) *CourseVersionsUpdateOne {
	return _u.SetTemplateID(v.ID)
}

// AddSyllabiIDs adds the "syllabi" edge to the Syllabi entity by IDs.
func (_u *CourseVersionsUpdateOne) AddSyllabiIDs(ids ...string) *CourseVersionsUpdateOne {
	_u.mutation.AddSyllabiIDs(ids...)
	return _u
}

// AddSyllabi adds the "syllabi" edges to the Syllabi entity.
func (_u *CourseVersionsUpdateOne) AddSyllabi(v ...*Syllabi) *CourseVersionsUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSyllabiIDs(ids...)
}

// Mutation returns the CourseVersionsMutation object of the builder.
func (_u *CourseVersionsUpdateOne) Mutation() *CourseVersionsMutation {
	return _u.mutation
}

// ClearTemplate clears the "template" edge to the CourseTemplates entity.
func (_u *CourseVersionsUpdateOne) ClearTemplate() *CourseVersionsUpdateOne {
	_u.mutation.ClearTemplate()
	return _u
}

// ClearSyllabi clears all "syllabi" edges to the Syllabi entity.
func (_u *CourseVersionsUpdateOne) ClearSyllabi() *CourseVersionsUpdateOne {
	_u.mutation.ClearSyllabi()
	return _u
}

// RemoveSyllabiIDs removes the "syllabi" edge to Syllabi entities by IDs.
func (_u *CourseVersionsUpdateOne) RemoveSyllabiIDs(ids ...string) *CourseVersionsUpdateOne {
	_u.mutation.RemoveSyllabiIDs(ids...)
	return _u
}

// RemoveSyllabi removes "syllabi" edges to Syllabi entities.
func (_u *CourseVersionsUpdateOne) RemoveSyllabi(v ...*Syllabi) *CourseVersionsUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSyllabiIDs(ids...)
}

// Where appends a list predicates to the CourseVersionsUpdate builder.
func (_u *CourseVersionsUpdateOne) Where(ps ...predicate.CourseVersions) *CourseVersionsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CourseVersionsUpdateOne) Select(field string, fields ...string) *CourseVersionsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CourseVersions entity.
func (_u *CourseVersionsUpdateOne) Save(ctx context.Context) (*CourseVersions, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CourseVersionsUpdateOne) SaveX(ctx context.Context) *CourseVersions {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CourseVersionsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CourseVersionsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CourseVersionsUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := courseversions.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CourseVersionsUpdateOne) check() error {
	if v, ok := _u.mutation.TemplateID(); ok {
		if err := courseversions.TemplateIDValidator(v); err != nil {
			return &ValidationError{Name: "template_id", err: fmt.Errorf(`ent: validator failed for field "CourseVersions.template_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VersionTag(); ok {
		if err := courseversions.VersionTagValidator(v); err != nil {
			return &ValidationError{Name: "version_tag", err: fmt.Errorf(`ent: validator failed for field "CourseVersions.version_tag": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := courseversions.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CourseVersions.status": %w`, err)}
		}
	}
	if _u.mutation.TemplateCleared() && len(_u.mutation.TemplateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CourseVersions.template"`)
	}
	return nil
}

func (_u *CourseVersionsUpdateOne) sqlSave(ctx context.Context) (_node *CourseVersions, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(courseversions.Table, courseversions.Columns, sqlgraph.NewFieldSpec(courseversions.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CourseVersions.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, courseversions.FieldID)
		for _, f := range fields {
			if !courseversions.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != courseversions.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(courseversions.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.VersionTag(); ok {
		_spec.SetField(courseversions.FieldVersionTag, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(courseversions.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.EstimatedHours(); ok {
		_spec.SetField(courseversions.FieldEstimatedHours, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEstimatedHours(); ok {
		_spec.AddField(courseversions.FieldEstimatedHours, field.TypeInt, value)
	}
	if _u.mutation.TemplateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   courseversions.TemplateTable,
			Columns: []string{courseversions.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coursetemplates.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   courseversions.TemplateTable,
			Columns: []string{courseversions.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coursetemplates.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SyllabiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courseversions.SyllabiTable,
			Columns: []string{courseversions.SyllabiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syllabi.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSyllabiIDs(); len(nodes) > 0 && !_u.mutation.SyllabiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courseversions.SyllabiTable,
			Columns: []string{courseversions.SyllabiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syllabi.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SyllabiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courseversions.SyllabiTable,
			Columns: []string{courseversions.SyllabiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syllabi.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CourseVersions{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{courseversions.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
