// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hexagonal-go-backend/internal/ent/tenantmixin"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TenantMixinCreate is the builder for creating a TenantMixin entity.
type TenantMixinCreate struct {
	config
	mutation *TenantMixinMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *TenantMixinCreate) SetTenantID(v string) *TenantMixinCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// Mutation returns the TenantMixinMutation object of the builder.
func (_c *TenantMixinCreate) Mutation() *TenantMixinMutation {
	return _c.mutation
}

// Save creates the TenantMixin in the database.
func (_c *TenantMixinCreate) Save(ctx context.Context) (*TenantMixin, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TenantMixinCreate) SaveX(ctx context.Context) *TenantMixin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantMixinCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantMixinCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TenantMixinCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "TenantMixin.tenant_id"`)}
	}
	if v, ok := _c.mutation.TenantID(); ok {
		if err := tenantmixin.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "TenantMixin.tenant_id": %w`, err)}
		}
	}
	return nil
}

func (_c *TenantMixinCreate) sqlSave(ctx context.Context) (*TenantMixin, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TenantMixinCreate) createSpec() (*TenantMixin, *sqlgraph.CreateSpec) {
	var (
		_node = &TenantMixin{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tenantmixin.Table, sqlgraph.NewFieldSpec(tenantmixin.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(tenantmixin.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	return _node, _spec
}

// TenantMixinCreateBulk is the builder for creating many TenantMixin entities in bulk.
type TenantMixinCreateBulk struct {
	config
	err      error
	builders []*TenantMixinCreate
}

// Save creates the TenantMixin entities in the database.
func (_c *TenantMixinCreateBulk) Save(ctx context.Context) ([]*TenantMixin, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TenantMixin, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TenantMixinMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TenantMixinCreateBulk) SaveX(ctx context.Context) []*TenantMixin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantMixinCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantMixinCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
