// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hexagonal-go-backend/internal/ent/tenants"
	"hexagonal-go-backend/internal/ent/tenantsettings"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TenantSettingsCreate is the builder for creating a TenantSettings entity.
type TenantSettingsCreate struct {
	config
	mutation *TenantSettingsMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *TenantSettingsCreate) SetCreatedAt(v time.Time) *TenantSettingsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TenantSettingsCreate) SetNillableCreatedAt(v *time.Time) *TenantSettingsCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TenantSettingsCreate) SetUpdatedAt(v time.Time) *TenantSettingsCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TenantSettingsCreate) SetNillableUpdatedAt(v *time.Time) *TenantSettingsCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTimezone sets the "timezone" field.
func (_c *TenantSettingsCreate) SetTimezone(v string) *TenantSettingsCreate {
	_c.mutation.SetTimezone(v)
	return _c
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_c *TenantSettingsCreate) SetNillableTimezone(v *string) *TenantSettingsCreate {
	if v != nil {
		_c.SetTimezone(*v)
	}
	return _c
}

// SetLanguage sets the "language" field.
func (_c *TenantSettingsCreate) SetLanguage(v string) *TenantSettingsCreate {
	_c.mutation.SetLanguage(v)
	return _c
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_c *TenantSettingsCreate) SetNillableLanguage(v *string) *TenantSettingsCreate {
	if v != nil {
		_c.SetLanguage(*v)
	}
	return _c
}

// SetDateFormat sets the "date_format" field.
func (_c *TenantSettingsCreate) SetDateFormat(v string) *TenantSettingsCreate {
	_c.mutation.SetDateFormat(v)
	return _c
}

// SetNillableDateFormat sets the "date_format" field if the given value is not nil.
func (_c *TenantSettingsCreate) SetNillableDateFormat(v *string) *TenantSettingsCreate {
	if v != nil {
		_c.SetDateFormat(*v)
	}
	return _c
}

// SetInstitutionalEmail sets the "institutional_email" field.
func (_c *TenantSettingsCreate) SetInstitutionalEmail(v string) *TenantSettingsCreate {
	_c.mutation.SetInstitutionalEmail(v)
	return _c
}

// SetNillableInstitutionalEmail sets the "institutional_email" field if the given value is not nil.
func (_c *TenantSettingsCreate) SetNillableInstitutionalEmail(v *string) *TenantSettingsCreate {
	if v != nil {
		_c.SetInstitutionalEmail(*v)
	}
	return _c
}

// SetPolicies sets the "policies" field.
func (_c *TenantSettingsCreate) SetPolicies(v map[string]interface{}) *TenantSettingsCreate {
	_c.mutation.SetPolicies(v)
	return _c
}

// SetFeatureFlags sets the "feature_flags" field.
func (_c *TenantSettingsCreate) SetFeatureFlags(v map[string]interface{}) *TenantSettingsCreate {
	_c.mutation.SetFeatureFlags(v)
	return _c
}

// SetID sets the "id" field.
func (_c *TenantSettingsCreate) SetID(v string) *TenantSettingsCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTenantID sets the "tenant" edge to the Tenants entity by ID.
func (_c *TenantSettingsCreate) SetTenantID(id string) *TenantSettingsCreate {
	_c.mutation.SetTenantID(id)
	return _c
}

// SetNillableTenantID sets the "tenant" edge to the Tenants entity by ID if the given value is not nil.
func (_c *TenantSettingsCreate) SetNillableTenantID(id *string) *TenantSettingsCreate {
	if id != nil {
		_c = _c.SetTenantID(*id)
	}
	return _c
}

// SetTenant sets the "tenant" edge to the Tenants entity.
func (_c *TenantSettingsCreate) SetTenant(v *Tenants) *TenantSettingsCreate {
	return _c.SetTenantID(v.ID)
}

// Mutation returns the TenantSettingsMutation object of the builder.
func (_c *TenantSettingsCreate) Mutation() *TenantSettingsMutation {
	return _c.mutation
}

// Save creates the TenantSettings in the database.
func (_c *TenantSettingsCreate) Save(ctx context.Context) (*TenantSettings, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TenantSettingsCreate) SaveX(ctx context.Context) *TenantSettings {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantSettingsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantSettingsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TenantSettingsCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := tenantsettings.DefaultCreatedAt
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := tenantsettings.DefaultUpdatedAt
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		v := tenantsettings.DefaultTimezone
		_c.mutation.SetTimezone(v)
	}
	if _, ok := _c.mutation.Language(); !ok {
		v := tenantsettings.DefaultLanguage
		_c.mutation.SetLanguage(v)
	}
	if _, ok := _c.mutation.DateFormat(); !ok {
		v := tenantsettings.DefaultDateFormat
		_c.mutation.SetDateFormat(v)
	}
	if _, ok := _c.mutation.InstitutionalEmail(); !ok {
		v := tenantsettings.DefaultInstitutionalEmail
		_c.mutation.SetInstitutionalEmail(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TenantSettingsCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TenantSettings.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TenantSettings.updated_at"`)}
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		return &ValidationError{Name: "timezone", err: errors.New(`ent: missing required field "TenantSettings.timezone"`)}
	}
	if v, ok := _c.mutation.Timezone(); ok {
		if err := tenantsettings.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "TenantSettings.timezone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Language(); !ok {
		return &ValidationError{Name: "language", err: errors.New(`ent: missing required field "TenantSettings.language"`)}
	}
	if v, ok := _c.mutation.Language(); ok {
		if err := tenantsettings.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "TenantSettings.language": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DateFormat(); !ok {
		return &ValidationError{Name: "date_format", err: errors.New(`ent: missing required field "TenantSettings.date_format"`)}
	}
	if v, ok := _c.mutation.DateFormat(); ok {
		if err := tenantsettings.DateFormatValidator(v); err != nil {
			return &ValidationError{Name: "date_format", err: fmt.Errorf(`ent: validator failed for field "TenantSettings.date_format": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InstitutionalEmail(); !ok {
		return &ValidationError{Name: "institutional_email", err: errors.New(`ent: missing required field "TenantSettings.institutional_email"`)}
	}
	if v, ok := _c.mutation.InstitutionalEmail(); ok {
		if err := tenantsettings.InstitutionalEmailValidator(v); err != nil {
			return &ValidationError{Name: "institutional_email", err: fmt.Errorf(`ent: validator failed for field "TenantSettings.institutional_email": %w`, err)}
		}
	}
	return nil
}

func (_c *TenantSettingsCreate) sqlSave(ctx context.Context) (*TenantSettings, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected TenantSettings.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TenantSettingsCreate) createSpec() (*TenantSettings, *sqlgraph.CreateSpec) {
	var (
		_node = &TenantSettings{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tenantsettings.Table, sqlgraph.NewFieldSpec(tenantsettings.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tenantsettings.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantsettings.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Timezone(); ok {
		_spec.SetField(tenantsettings.FieldTimezone, field.TypeString, value)
		_node.Timezone = value
	}
	if value, ok := _c.mutation.Language(); ok {
		_spec.SetField(tenantsettings.FieldLanguage, field.TypeString, value)
		_node.Language = value
	}
	if value, ok := _c.mutation.DateFormat(); ok {
		_spec.SetField(tenantsettings.FieldDateFormat, field.TypeString, value)
		_node.DateFormat = value
	}
	if value, ok := _c.mutation.InstitutionalEmail(); ok {
		_spec.SetField(tenantsettings.FieldInstitutionalEmail, field.TypeString, value)
		_node.InstitutionalEmail = value
	}
	if value, ok := _c.mutation.Policies(); ok {
		_spec.SetField(tenantsettings.FieldPolicies, field.TypeJSON, value)
		_node.Policies = value
	}
	if value, ok := _c.mutation.FeatureFlags(); ok {
		_spec.SetField(tenantsettings.FieldFeatureFlags, field.TypeJSON, value)
		_node.FeatureFlags = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   tenantsettings.TenantTable,
			Columns: []string{tenantsettings.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenants.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.tenants_settings = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TenantSettingsCreateBulk is the builder for creating many TenantSettings entities in bulk.
type TenantSettingsCreateBulk struct {
	config
	err      error
	builders []*TenantSettingsCreate
}

// Save creates the TenantSettings entities in the database.
func (_c *TenantSettingsCreateBulk) Save(ctx context.Context) ([]*TenantSettings, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TenantSettings, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TenantSettingsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TenantSettingsCreateBulk) SaveX(ctx context.Context) []*TenantSettings {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantSettingsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantSettingsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
