// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hexagonal-go-backend/internal/ent/predicate"
	"hexagonal-go-backend/internal/ent/tenants"
	"hexagonal-go-backend/internal/ent/tenantsettings"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TenantSettingsUpdate is the builder for updating TenantSettings entities.
type TenantSettingsUpdate struct {
	config
	hooks    []Hook
	mutation *TenantSettingsMutation
}

// Where appends a list predicates to the TenantSettingsUpdate builder.
func (_u *TenantSettingsUpdate) Where(ps ...predicate.TenantSettings) *TenantSettingsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantSettingsUpdate) SetUpdatedAt(v time.Time) *TenantSettingsUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *TenantSettingsUpdate) SetTimezone(v string) *TenantSettingsUpdate {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *TenantSettingsUpdate) SetNillableTimezone(v *string) *TenantSettingsUpdate {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *TenantSettingsUpdate) SetLanguage(v string) *TenantSettingsUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *TenantSettingsUpdate) SetNillableLanguage(v *string) *TenantSettingsUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetDateFormat sets the "date_format" field.
func (_u *TenantSettingsUpdate) SetDateFormat(v string) *TenantSettingsUpdate {
	_u.mutation.SetDateFormat(v)
	return _u
}

// SetNillableDateFormat sets the "date_format" field if the given value is not nil.
func (_u *TenantSettingsUpdate) SetNillableDateFormat(v *string) *TenantSettingsUpdate {
	if v != nil {
		_u.SetDateFormat(*v)
	}
	return _u
}

// SetInstitutionalEmail sets the "institutional_email" field.
func (_u *TenantSettingsUpdate) SetInstitutionalEmail(v string) *TenantSettingsUpdate {
	_u.mutation.SetInstitutionalEmail(v)
	return _u
}

// SetNillableInstitutionalEmail sets the "institutional_email" field if the given value is not nil.
func (_u *TenantSettingsUpdate) SetNillableInstitutionalEmail(v *string) *TenantSettingsUpdate {
	if v != nil {
		_u.SetInstitutionalEmail(*v)
	}
	return _u
}

// SetPolicies sets the "policies" field.
func (_u *TenantSettingsUpdate) SetPolicies(v map[string]interface{}) *TenantSettingsUpdate {
	_u.mutation.SetPolicies(v)
	return _u
}

// ClearPolicies clears the value of the "policies" field.
func (_u *TenantSettingsUpdate) ClearPolicies() *TenantSettingsUpdate {
	_u.mutation.ClearPolicies()
	return _u
}

// SetFeatureFlags sets the "feature_flags" field.
func (_u *TenantSettingsUpdate) SetFeatureFlags(v map[string]interface{}) *TenantSettingsUpdate {
	_u.mutation.SetFeatureFlags(v)
	return _u
}

// ClearFeatureFlags clears the value of the "feature_flags" field.
func (_u *TenantSettingsUpdate) ClearFeatureFlags() *TenantSettingsUpdate {
	_u.mutation.ClearFeatureFlags()
	return _u
}

// SetTenantID sets the "tenant" edge to the Tenants entity by ID.
func (_u *TenantSettingsUpdate) SetTenantID(id string) *TenantSettingsUpdate {
	_u.mutation.SetTenantID(id)
	return _u
}

// SetNillableTenantID sets the "tenant" edge to the Tenants entity by ID if the given value is not nil.
func (_u *TenantSettingsUpdate) SetNillableTenantID(id *string) *TenantSettingsUpdate {
	if id != nil {
		_u = _u.SetTenantID(*id)
	}
	return _u
}

// SetTenant sets the "tenant" edge to the Tenants entity.
func (_u *TenantSettingsUpdate) SetTenant(v *Tenants) *TenantSettingsUpdate {
	return _u.SetTenantID(v.ID)
}

// Mutation returns the TenantSettingsMutation object of the builder.
func (_u *TenantSettingsUpdate) Mutation() *TenantSettingsMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenants entity.
func (_u *TenantSettingsUpdate) ClearTenant() *TenantSettingsUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TenantSettingsUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantSettingsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TenantSettingsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantSettingsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantSettingsUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenantsettings.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantSettingsUpdate) check() error {
	if v, ok := _u.mutation.Timezone(); ok {
		if err := tenantsettings.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "TenantSettings.timezone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Language(); ok {
		if err := tenantsettings.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "TenantSettings.language": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DateFormat(); ok {
		if err := tenantsettings.DateFormatValidator(v); err != nil {
			return &ValidationError{Name: "date_format", err: fmt.Errorf(`ent: validator failed for field "TenantSettings.date_format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InstitutionalEmail(); ok {
		if err := tenantsettings.InstitutionalEmailValidator(v); err != nil {
			return &ValidationError{Name: "institutional_email", err: fmt.Errorf(`ent: validator failed for field "TenantSettings.institutional_email": %w`, err)}
		}
	}
	return nil
}

func (_u *TenantSettingsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenantsettings.Table, tenantsettings.Columns, sqlgraph.NewFieldSpec(tenantsettings.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantsettings.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(tenantsettings.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(tenantsettings.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.DateFormat(); ok {
		_spec.SetField(tenantsettings.FieldDateFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.InstitutionalEmail(); ok {
		_spec.SetField(tenantsettings.FieldInstitutionalEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Policies(); ok {
		_spec.SetField(tenantsettings.FieldPolicies, field.TypeJSON, value)
	}
	if _u.mutation.PoliciesCleared() {
		_spec.ClearField(tenantsettings.FieldPolicies, field.TypeJSON)
	}
	if value, ok := _u.mutation.FeatureFlags(); ok {
		_spec.SetField(tenantsettings.FieldFeatureFlags, field.TypeJSON, value)
	}
	if _u.mutation.FeatureFlagsCleared() {
		_spec.ClearField(tenantsettings.FieldFeatureFlags, field.TypeJSON)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   tenantsettings.TenantTable,
			Columns: []string{tenantsettings.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenants.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   tenantsettings.TenantTable,
			Columns: []string{tenantsettings.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenants.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantsettings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TenantSettingsUpdateOne is the builder for updating a single TenantSettings entity.
type TenantSettingsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenantSettingsMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantSettingsUpdateOne) SetUpdatedAt(v time.Time) *TenantSettingsUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *TenantSettingsUpdateOne) SetTimezone(v string) *TenantSettingsUpdateOne {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *TenantSettingsUpdateOne) SetNillableTimezone(v *string) *TenantSettingsUpdateOne {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *TenantSettingsUpdateOne) SetLanguage(v string) *TenantSettingsUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *TenantSettingsUpdateOne) SetNillableLanguage(v *string) *TenantSettingsUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetDateFormat sets the "date_format" field.
func (_u *TenantSettingsUpdateOne) SetDateFormat(v string) *TenantSettingsUpdateOne {
	_u.mutation.SetDateFormat(v)
	return _u
}

// SetNillableDateFormat sets the "date_format" field if the given value is not nil.
func (_u *TenantSettingsUpdateOne) SetNillableDateFormat(v *string) *TenantSettingsUpdateOne {
	if v != nil {
		_u.SetDateFormat(*v)
	}
	return _u
}

// SetInstitutionalEmail sets the "institutional_email" field.
func (_u *TenantSettingsUpdateOne) SetInstitutionalEmail(v string) *TenantSettingsUpdateOne {
	_u.mutation.SetInstitutionalEmail(v)
	return _u
}

// SetNillableInstitutionalEmail sets the "institutional_email" field if the given value is not nil.
func (_u *TenantSettingsUpdateOne) SetNillableInstitutionalEmail(v *string) *TenantSettingsUpdateOne {
	if v != nil {
		_u.SetInstitutionalEmail(*v)
	}
	return _u
}

// SetPolicies sets the "policies" field.
func (_u *TenantSettingsUpdateOne) SetPolicies(v map[string]interface{}) *TenantSettingsUpdateOne {
	_u.mutation.SetPolicies(v)
	return _u
}

// ClearPolicies clears the value of the "policies" field.
func (_u *TenantSettingsUpdateOne) ClearPolicies() *TenantSettingsUpdateOne {
	_u.mutation.ClearPolicies()
	return _u
}

// SetFeatureFlags sets the "feature_flags" field.
func (_u *TenantSettingsUpdateOne) SetFeatureFlags(v map[string]interface{}) *TenantSettingsUpdateOne {
	_u.mutation.SetFeatureFlags(v)
	return _u
}

// ClearFeatureFlags clears the value of the "feature_flags" field.
func (_u *TenantSettingsUpdateOne) ClearFeatureFlags() *TenantSettingsUpdateOne {
	_u.mutation.ClearFeatureFlags()
	return _u
}

// SetTenantID sets the "tenant" edge to the Tenants entity by ID.
func (_u *TenantSettingsUpdateOne) SetTenantID(id string) *TenantSettingsUpdateOne {
	_u.mutation.SetTenantID(id)
	return _u
}

// SetNillableTenantID sets the "tenant" edge to the Tenants entity by ID if the given value is not nil.
func (_u *TenantSettingsUpdateOne) SetNillableTenantID(id *string) *TenantSettingsUpdateOne {
	if id != nil {
		_u = _u.SetTenantID(*id)
	}
	return _u
}

// SetTenant sets the "tenant" edge to the Tenants entity.
func (_u *TenantSettingsUpdateOne) SetTenant(v *Tenants) *TenantSettingsUpdateOne {
	return _u.SetTenantID(v.ID)
}

// Mutation returns the TenantSettingsMutation object of the builder.
func (_u *TenantSettingsUpdateOne) Mutation() *TenantSettingsMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenants entity.
func (_u *TenantSettingsUpdateOne) ClearTenant() *TenantSettingsUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// Where appends a list predicates to the TenantSettingsUpdate builder.
func (_u *TenantSettingsUpdateOne) Where(ps ...predicate.TenantSettings) *TenantSettingsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TenantSettingsUpdateOne) Select(field string, fields ...string) *TenantSettingsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TenantSettings entity.
func (_u *TenantSettingsUpdateOne) Save(ctx context.Context) (*TenantSettings, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantSettingsUpdateOne) SaveX(ctx context.Context) *TenantSettings {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TenantSettingsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantSettingsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantSettingsUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenantsettings.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantSettingsUpdateOne) check() error {
	if v, ok := _u.mutation.Timezone(); ok {
		if err := tenantsettings.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "TenantSettings.timezone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Language(); ok {
		if err := tenantsettings.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "TenantSettings.language": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DateFormat(); ok {
		if err := tenantsettings.DateFormatValidator(v); err != nil {
			return &ValidationError{Name: "date_format", err: fmt.Errorf(`ent: validator failed for field "TenantSettings.date_format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InstitutionalEmail(); ok {
		if err := tenantsettings.InstitutionalEmailValidator(v); err != nil {
			return &ValidationError{Name: "institutional_email", err: fmt.Errorf(`ent: validator failed for field "TenantSettings.institutional_email": %w`, err)}
		}
	}
	return nil
}

func (_u *TenantSettingsUpdateOne) sqlSave(ctx context.Context) (_node *TenantSettings, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenantsettings.Table, tenantsettings.Columns, sqlgraph.NewFieldSpec(tenantsettings.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TenantSettings.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenantsettings.FieldID)
		for _, f := range fields {
			if !tenantsettings.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenantsettings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantsettings.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(tenantsettings.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(tenantsettings.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.DateFormat(); ok {
		_spec.SetField(tenantsettings.FieldDateFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.InstitutionalEmail(); ok {
		_spec.SetField(tenantsettings.FieldInstitutionalEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Policies(); ok {
		_spec.SetField(tenantsettings.FieldPolicies, field.TypeJSON, value)
	}
	if _u.mutation.PoliciesCleared() {
		_spec.ClearField(tenantsettings.FieldPolicies, field.TypeJSON)
	}
	if value, ok := _u.mutation.FeatureFlags(); ok {
		_spec.SetField(tenantsettings.FieldFeatureFlags, field.TypeJSON, value)
	}
	if _u.mutation.FeatureFlagsCleared() {
		_spec.ClearField(tenantsettings.FieldFeatureFlags, field.TypeJSON)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   tenantsettings.TenantTable,
			Columns: []string{tenantsettings.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenants.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   tenantsettings.TenantTable,
			Columns: []string{tenantsettings.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenants.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TenantSettings{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantsettings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
