// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"hexagonal-go-backend/internal/ent/tenants"
	"hexagonal-go-backend/internal/ent/tenantsettings"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Tenants is the model entity for the Tenants schema.
type Tenants struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Branding holds the value of the "branding" field.
	Branding map[string]interface{} `json:"branding,omitempty"`
	// Domains holds the value of the "domains" field.
	Domains []string `json:"domains,omitempty"`
	// Limits holds the value of the "limits" field.
	Limits map[string]interface{} `json:"limits,omitempty"`
	// Features holds the value of the "features" field.
	Features map[string]interface{} `json:"features,omitempty"`
	// Status holds the value of the "status" field.
	Status tenants.Status `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TenantsQuery when eager-loading is set.
	Edges        TenantsEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TenantsEdges holds the relations/edges for other nodes in the graph.
type TenantsEdges struct {
	// Settings holds the value of the settings edge.
	Settings *TenantSettings `json:"settings,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SettingsOrErr returns the Settings value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TenantsEdges) SettingsOrErr() (*TenantSettings, error) {
	if e.Settings != nil {
		return e.Settings, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenantsettings.Label}
	}
	return nil, &NotLoadedError{edge: "settings"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Tenants) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tenants.FieldBranding, tenants.FieldDomains, tenants.FieldLimits, tenants.FieldFeatures:
			values[i] = new([]byte)
		case tenants.FieldID, tenants.FieldName, tenants.FieldStatus:
			values[i] = new(sql.NullString)
		case tenants.FieldCreatedAt, tenants.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Tenants fields.
func (_m *Tenants) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tenants.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case tenants.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case tenants.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case tenants.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case tenants.FieldBranding:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field branding", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Branding); err != nil {
					return fmt.Errorf("unmarshal field branding: %w", err)
				}
			}
		case tenants.FieldDomains:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field domains", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Domains); err != nil {
					return fmt.Errorf("unmarshal field domains: %w", err)
				}
			}
		case tenants.FieldLimits:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field limits", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Limits); err != nil {
					return fmt.Errorf("unmarshal field limits: %w", err)
				}
			}
		case tenants.FieldFeatures:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field features", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Features); err != nil {
					return fmt.Errorf("unmarshal field features: %w", err)
				}
			}
		case tenants.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = tenants.Status(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Tenants.
// This includes values selected through modifiers, order, etc.
func (_m *Tenants) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySettings queries the "settings" edge of the Tenants entity.
func (_m *Tenants) QuerySettings() *TenantSettingsQuery {
	return NewTenantsClient(_m.config).QuerySettings(_m)
}

// Update returns a builder for updating this Tenants.
// Note that you need to call Tenants.Unwrap() before calling this method if this Tenants
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Tenants) Update() *TenantsUpdateOne {
	return NewTenantsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Tenants entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Tenants) Unwrap() *Tenants {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Tenants is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Tenants) String() string {
	var builder strings.Builder
	builder.WriteString("Tenants(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("branding=")
	builder.WriteString(fmt.Sprintf("%v", _m.Branding))
	builder.WriteString(", ")
	builder.WriteString("domains=")
	builder.WriteString(fmt.Sprintf("%v", _m.Domains))
	builder.WriteString(", ")
	builder.WriteString("limits=")
	builder.WriteString(fmt.Sprintf("%v", _m.Limits))
	builder.WriteString(", ")
	builder.WriteString("features=")
	builder.WriteString(fmt.Sprintf("%v", _m.Features))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteByte(')')
	return builder.String()
}

// TenantsSlice is a parsable slice of Tenants.
type TenantsSlice []*Tenants
