// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"hexagonal-go-backend/internal/ent/predicate"
	"hexagonal-go-backend/internal/ent/tenants"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TenantsDelete is the builder for deleting a Tenants entity.
type TenantsDelete struct {
	config
	hooks    []Hook
	mutation *TenantsMutation
}

// Where appends a list predicates to the TenantsDelete builder.
func (_d *TenantsDelete) Where(ps ...predicate.Tenants) *TenantsDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TenantsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TenantsDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TenantsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tenants.Table, sqlgraph.NewFieldSpec(tenants.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TenantsDeleteOne is the builder for deleting a single Tenants entity.
type TenantsDeleteOne struct {
	_d *TenantsDelete
}

// Where appends a list predicates to the TenantsDelete builder.
func (_d *TenantsDeleteOne) Where(ps ...predicate.Tenants) *TenantsDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TenantsDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tenants.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TenantsDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
