// Code generated by ent, DO NOT EDIT.

package courseversions

import (
	"hexagonal-go-backend/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldEQ(FieldUpdatedAt, v))
}

// TemplateID applies equality check predicate on the "template_id" field. It's identical to TemplateIDEQ.
func TemplateID(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldEQ(FieldTemplateID, v))
}

// VersionTag applies equality check predicate on the "version_tag" field. It's identical to VersionTagEQ.
func VersionTag(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldEQ(FieldVersionTag, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldEQ(FieldStatus, v))
}

// EstimatedHours applies equality check predicate on the "estimated_hours" field. It's identical to EstimatedHoursEQ.
func EstimatedHours(v int) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldEQ(FieldEstimatedHours, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldLTE(FieldUpdatedAt, v))
}

// TemplateIDEQ applies the EQ predicate on the "template_id" field.
func TemplateIDEQ(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldEQ(FieldTemplateID, v))
}

// TemplateIDNEQ applies the NEQ predicate on the "template_id" field.
func TemplateIDNEQ(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldNEQ(FieldTemplateID, v))
}

// TemplateIDIn applies the In predicate on the "template_id" field.
func TemplateIDIn(vs ...string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldIn(FieldTemplateID, vs...))
}

// TemplateIDNotIn applies the NotIn predicate on the "template_id" field.
func TemplateIDNotIn(vs ...string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldNotIn(FieldTemplateID, vs...))
}

// TemplateIDGT applies the GT predicate on the "template_id" field.
func TemplateIDGT(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldGT(FieldTemplateID, v))
}

// TemplateIDGTE applies the GTE predicate on the "template_id" field.
func TemplateIDGTE(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldGTE(FieldTemplateID, v))
}

// TemplateIDLT applies the LT predicate on the "template_id" field.
func TemplateIDLT(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldLT(FieldTemplateID, v))
}

// TemplateIDLTE applies the LTE predicate on the "template_id" field.
func TemplateIDLTE(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldLTE(FieldTemplateID, v))
}

// TemplateIDContains applies the Contains predicate on the "template_id" field.
func TemplateIDContains(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldContains(FieldTemplateID, v))
}

// TemplateIDHasPrefix applies the HasPrefix predicate on the "template_id" field.
func TemplateIDHasPrefix(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldHasPrefix(FieldTemplateID, v))
}

// TemplateIDHasSuffix applies the HasSuffix predicate on the "template_id" field.
func TemplateIDHasSuffix(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldHasSuffix(FieldTemplateID, v))
}

// TemplateIDEqualFold applies the EqualFold predicate on the "template_id" field.
func TemplateIDEqualFold(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldEqualFold(FieldTemplateID, v))
}

// TemplateIDContainsFold applies the ContainsFold predicate on the "template_id" field.
func TemplateIDContainsFold(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldContainsFold(FieldTemplateID, v))
}

// VersionTagEQ applies the EQ predicate on the "version_tag" field.
func VersionTagEQ(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldEQ(FieldVersionTag, v))
}

// VersionTagNEQ applies the NEQ predicate on the "version_tag" field.
func VersionTagNEQ(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldNEQ(FieldVersionTag, v))
}

// VersionTagIn applies the In predicate on the "version_tag" field.
func VersionTagIn(vs ...string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldIn(FieldVersionTag, vs...))
}

// VersionTagNotIn applies the NotIn predicate on the "version_tag" field.
func VersionTagNotIn(vs ...string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldNotIn(FieldVersionTag, vs...))
}

// VersionTagGT applies the GT predicate on the "version_tag" field.
func VersionTagGT(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldGT(FieldVersionTag, v))
}

// VersionTagGTE applies the GTE predicate on the "version_tag" field.
func VersionTagGTE(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldGTE(FieldVersionTag, v))
}

// VersionTagLT applies the LT predicate on the "version_tag" field.
func VersionTagLT(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldLT(FieldVersionTag, v))
}

// VersionTagLTE applies the LTE predicate on the "version_tag" field.
func VersionTagLTE(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldLTE(FieldVersionTag, v))
}

// VersionTagContains applies the Contains predicate on the "version_tag" field.
func VersionTagContains(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldContains(FieldVersionTag, v))
}

// VersionTagHasPrefix applies the HasPrefix predicate on the "version_tag" field.
func VersionTagHasPrefix(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldHasPrefix(FieldVersionTag, v))
}

// VersionTagHasSuffix applies the HasSuffix predicate on the "version_tag" field.
func VersionTagHasSuffix(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldHasSuffix(FieldVersionTag, v))
}

// VersionTagEqualFold applies the EqualFold predicate on the "version_tag" field.
func VersionTagEqualFold(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldEqualFold(FieldVersionTag, v))
}

// VersionTagContainsFold applies the ContainsFold predicate on the "version_tag" field.
func VersionTagContainsFold(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldContainsFold(FieldVersionTag, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldContainsFold(FieldStatus, v))
}

// EstimatedHoursEQ applies the EQ predicate on the "estimated_hours" field.
func EstimatedHoursEQ(v int) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldEQ(FieldEstimatedHours, v))
}

// EstimatedHoursNEQ applies the NEQ predicate on the "estimated_hours" field.
func EstimatedHoursNEQ(v int) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldNEQ(FieldEstimatedHours, v))
}

// EstimatedHoursIn applies the In predicate on the "estimated_hours" field.
func EstimatedHoursIn(vs ...int) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldIn(FieldEstimatedHours, vs...))
}

// EstimatedHoursNotIn applies the NotIn predicate on the "estimated_hours" field.
func EstimatedHoursNotIn(vs ...int) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldNotIn(FieldEstimatedHours, vs...))
}

// EstimatedHoursGT applies the GT predicate on the "estimated_hours" field.
func EstimatedHoursGT(v int) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldGT(FieldEstimatedHours, v))
}

// EstimatedHoursGTE applies the GTE predicate on the "estimated_hours" field.
func EstimatedHoursGTE(v int) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldGTE(FieldEstimatedHours, v))
}

// EstimatedHoursLT applies the LT predicate on the "estimated_hours" field.
func EstimatedHoursLT(v int) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldLT(FieldEstimatedHours, v))
}

// EstimatedHoursLTE applies the LTE predicate on the "estimated_hours" field.
func EstimatedHoursLTE(v int) predicate.CourseVersions {
	return predicate.CourseVersions(sql.FieldLTE(FieldEstimatedHours, v))
}

// HasTemplate applies the HasEdge predicate on the "template" edge.
func HasTemplate() predicate.CourseVersions {
	return predicate.CourseVersions(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TemplateTable, TemplateColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTemplateWith applies the HasEdge predicate on the "template" edge with a given conditions (other predicates).
func HasTemplateWith(preds ...predicate.CourseTemplates) predicate.CourseVersions {
	return predicate.CourseVersions(func(s *sql.Selector) {
		step := newTemplateStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSyllabi applies the HasEdge predicate on the "syllabi" edge.
func HasSyllabi() predicate.CourseVersions {
	return predicate.CourseVersions(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SyllabiTable, SyllabiColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSyllabiWith applies the HasEdge predicate on the "syllabi" edge with a given conditions (other predicates).
func HasSyllabiWith(preds ...predicate.Syllabi) predicate.CourseVersions {
	return predicate.CourseVersions(func(s *sql.Selector) {
		step := newSyllabiStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CourseVersions) predicate.CourseVersions {
	return predicate.CourseVersions(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CourseVersions) predicate.CourseVersions {
	return predicate.CourseVersions(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CourseVersions) predicate.CourseVersions {
	return predicate.CourseVersions(sql.NotPredicates(p))
}
