// Code generated by ent, DO NOT EDIT.

package tenantsettings

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the tenantsettings type in the database.
	Label = "tenant_settings"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTimezone holds the string denoting the timezone field in the database.
	FieldTimezone = "timezone"
	// FieldLanguage holds the string denoting the language field in the database.
	FieldLanguage = "language"
	// FieldDateFormat holds the string denoting the date_format field in the database.
	FieldDateFormat = "date_format"
	// FieldInstitutionalEmail holds the string denoting the institutional_email field in the database.
	FieldInstitutionalEmail = "institutional_email"
	// FieldPolicies holds the string denoting the policies field in the database.
	FieldPolicies = "policies"
	// FieldFeatureFlags holds the string denoting the feature_flags field in the database.
	FieldFeatureFlags = "feature_flags"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// Table holds the table name of the tenantsettings in the database.
	Table = "tenant_settings"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "tenant_settings"
	// TenantInverseTable is the table name for the Tenants entity.
	// It exists in this package in order to avoid circular dependency with the "tenants" package.
	TenantInverseTable = "tenants"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenants_settings"
)

// Columns holds all SQL columns for tenantsettings fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTimezone,
	FieldLanguage,
	FieldDateFormat,
	FieldInstitutionalEmail,
	FieldPolicies,
	FieldFeatureFlags,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "tenant_settings"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"tenants_settings",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultTimezone holds the default value on creation for the "timezone" field.
	DefaultTimezone string
	// TimezoneValidator is a validator for the "timezone" field. It is called by the builders before save.
	TimezoneValidator func(string) error
	// DefaultLanguage holds the default value on creation for the "language" field.
	DefaultLanguage string
	// LanguageValidator is a validator for the "language" field. It is called by the builders before save.
	LanguageValidator func(string) error
	// DefaultDateFormat holds the default value on creation for the "date_format" field.
	DefaultDateFormat string
	// DateFormatValidator is a validator for the "date_format" field. It is called by the builders before save.
	DateFormatValidator func(string) error
	// DefaultInstitutionalEmail holds the default value on creation for the "institutional_email" field.
	DefaultInstitutionalEmail string
	// InstitutionalEmailValidator is a validator for the "institutional_email" field. It is called by the builders before save.
	InstitutionalEmailValidator func(string) error
)

// OrderOption defines the ordering options for the TenantSettings queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTimezone orders the results by the timezone field.
func ByTimezone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimezone, opts...).ToFunc()
}

// ByLanguage orders the results by the language field.
func ByLanguage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLanguage, opts...).ToFunc()
}

// ByDateFormat orders the results by the date_format field.
func ByDateFormat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateFormat, opts...).ToFunc()
}

// ByInstitutionalEmail orders the results by the institutional_email field.
func ByInstitutionalEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstitutionalEmail, opts...).ToFunc()
}

// ByTenantField orders the results by tenant field.
func ByTenantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), sql.OrderByField(field, opts...))
	}
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, TenantTable, TenantColumn),
	)
}
