// Code generated by ent, DO NOT EDIT.

package tenantsettings

import (
	"hexagonal-go-backend/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldEQ(FieldUpdatedAt, v))
}

// Timezone applies equality check predicate on the "timezone" field. It's identical to TimezoneEQ.
func Timezone(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldEQ(FieldTimezone, v))
}

// Language applies equality check predicate on the "language" field. It's identical to LanguageEQ.
func Language(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldEQ(FieldLanguage, v))
}

// DateFormat applies equality check predicate on the "date_format" field. It's identical to DateFormatEQ.
func DateFormat(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldEQ(FieldDateFormat, v))
}

// InstitutionalEmail applies equality check predicate on the "institutional_email" field. It's identical to InstitutionalEmailEQ.
func InstitutionalEmail(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldEQ(FieldInstitutionalEmail, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldLTE(FieldUpdatedAt, v))
}

// TimezoneEQ applies the EQ predicate on the "timezone" field.
func TimezoneEQ(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldEQ(FieldTimezone, v))
}

// TimezoneNEQ applies the NEQ predicate on the "timezone" field.
func TimezoneNEQ(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldNEQ(FieldTimezone, v))
}

// TimezoneIn applies the In predicate on the "timezone" field.
func TimezoneIn(vs ...string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldIn(FieldTimezone, vs...))
}

// TimezoneNotIn applies the NotIn predicate on the "timezone" field.
func TimezoneNotIn(vs ...string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldNotIn(FieldTimezone, vs...))
}

// TimezoneGT applies the GT predicate on the "timezone" field.
func TimezoneGT(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldGT(FieldTimezone, v))
}

// TimezoneGTE applies the GTE predicate on the "timezone" field.
func TimezoneGTE(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldGTE(FieldTimezone, v))
}

// TimezoneLT applies the LT predicate on the "timezone" field.
func TimezoneLT(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldLT(FieldTimezone, v))
}

// TimezoneLTE applies the LTE predicate on the "timezone" field.
func TimezoneLTE(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldLTE(FieldTimezone, v))
}

// TimezoneContains applies the Contains predicate on the "timezone" field.
func TimezoneContains(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldContains(FieldTimezone, v))
}

// TimezoneHasPrefix applies the HasPrefix predicate on the "timezone" field.
func TimezoneHasPrefix(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldHasPrefix(FieldTimezone, v))
}

// TimezoneHasSuffix applies the HasSuffix predicate on the "timezone" field.
func TimezoneHasSuffix(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldHasSuffix(FieldTimezone, v))
}

// TimezoneEqualFold applies the EqualFold predicate on the "timezone" field.
func TimezoneEqualFold(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldEqualFold(FieldTimezone, v))
}

// TimezoneContainsFold applies the ContainsFold predicate on the "timezone" field.
func TimezoneContainsFold(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldContainsFold(FieldTimezone, v))
}

// LanguageEQ applies the EQ predicate on the "language" field.
func LanguageEQ(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldEQ(FieldLanguage, v))
}

// LanguageNEQ applies the NEQ predicate on the "language" field.
func LanguageNEQ(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldNEQ(FieldLanguage, v))
}

// LanguageIn applies the In predicate on the "language" field.
func LanguageIn(vs ...string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldIn(FieldLanguage, vs...))
}

// LanguageNotIn applies the NotIn predicate on the "language" field.
func LanguageNotIn(vs ...string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldNotIn(FieldLanguage, vs...))
}

// LanguageGT applies the GT predicate on the "language" field.
func LanguageGT(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldGT(FieldLanguage, v))
}

// LanguageGTE applies the GTE predicate on the "language" field.
func LanguageGTE(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldGTE(FieldLanguage, v))
}

// LanguageLT applies the LT predicate on the "language" field.
func LanguageLT(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldLT(FieldLanguage, v))
}

// LanguageLTE applies the LTE predicate on the "language" field.
func LanguageLTE(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldLTE(FieldLanguage, v))
}

// LanguageContains applies the Contains predicate on the "language" field.
func LanguageContains(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldContains(FieldLanguage, v))
}

// LanguageHasPrefix applies the HasPrefix predicate on the "language" field.
func LanguageHasPrefix(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldHasPrefix(FieldLanguage, v))
}

// LanguageHasSuffix applies the HasSuffix predicate on the "language" field.
func LanguageHasSuffix(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldHasSuffix(FieldLanguage, v))
}

// LanguageEqualFold applies the EqualFold predicate on the "language" field.
func LanguageEqualFold(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldEqualFold(FieldLanguage, v))
}

// LanguageContainsFold applies the ContainsFold predicate on the "language" field.
func LanguageContainsFold(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldContainsFold(FieldLanguage, v))
}

// DateFormatEQ applies the EQ predicate on the "date_format" field.
func DateFormatEQ(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldEQ(FieldDateFormat, v))
}

// DateFormatNEQ applies the NEQ predicate on the "date_format" field.
func DateFormatNEQ(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldNEQ(FieldDateFormat, v))
}

// DateFormatIn applies the In predicate on the "date_format" field.
func DateFormatIn(vs ...string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldIn(FieldDateFormat, vs...))
}

// DateFormatNotIn applies the NotIn predicate on the "date_format" field.
func DateFormatNotIn(vs ...string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldNotIn(FieldDateFormat, vs...))
}

// DateFormatGT applies the GT predicate on the "date_format" field.
func DateFormatGT(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldGT(FieldDateFormat, v))
}

// DateFormatGTE applies the GTE predicate on the "date_format" field.
func DateFormatGTE(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldGTE(FieldDateFormat, v))
}

// DateFormatLT applies the LT predicate on the "date_format" field.
func DateFormatLT(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldLT(FieldDateFormat, v))
}

// DateFormatLTE applies the LTE predicate on the "date_format" field.
func DateFormatLTE(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldLTE(FieldDateFormat, v))
}

// DateFormatContains applies the Contains predicate on the "date_format" field.
func DateFormatContains(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldContains(FieldDateFormat, v))
}

// DateFormatHasPrefix applies the HasPrefix predicate on the "date_format" field.
func DateFormatHasPrefix(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldHasPrefix(FieldDateFormat, v))
}

// DateFormatHasSuffix applies the HasSuffix predicate on the "date_format" field.
func DateFormatHasSuffix(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldHasSuffix(FieldDateFormat, v))
}

// DateFormatEqualFold applies the EqualFold predicate on the "date_format" field.
func DateFormatEqualFold(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldEqualFold(FieldDateFormat, v))
}

// DateFormatContainsFold applies the ContainsFold predicate on the "date_format" field.
func DateFormatContainsFold(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldContainsFold(FieldDateFormat, v))
}

// InstitutionalEmailEQ applies the EQ predicate on the "institutional_email" field.
func InstitutionalEmailEQ(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldEQ(FieldInstitutionalEmail, v))
}

// InstitutionalEmailNEQ applies the NEQ predicate on the "institutional_email" field.
func InstitutionalEmailNEQ(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldNEQ(FieldInstitutionalEmail, v))
}

// InstitutionalEmailIn applies the In predicate on the "institutional_email" field.
func InstitutionalEmailIn(vs ...string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldIn(FieldInstitutionalEmail, vs...))
}

// InstitutionalEmailNotIn applies the NotIn predicate on the "institutional_email" field.
func InstitutionalEmailNotIn(vs ...string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldNotIn(FieldInstitutionalEmail, vs...))
}

// InstitutionalEmailGT applies the GT predicate on the "institutional_email" field.
func InstitutionalEmailGT(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldGT(FieldInstitutionalEmail, v))
}

// InstitutionalEmailGTE applies the GTE predicate on the "institutional_email" field.
func InstitutionalEmailGTE(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldGTE(FieldInstitutionalEmail, v))
}

// InstitutionalEmailLT applies the LT predicate on the "institutional_email" field.
func InstitutionalEmailLT(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldLT(FieldInstitutionalEmail, v))
}

// InstitutionalEmailLTE applies the LTE predicate on the "institutional_email" field.
func InstitutionalEmailLTE(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldLTE(FieldInstitutionalEmail, v))
}

// InstitutionalEmailContains applies the Contains predicate on the "institutional_email" field.
func InstitutionalEmailContains(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldContains(FieldInstitutionalEmail, v))
}

// InstitutionalEmailHasPrefix applies the HasPrefix predicate on the "institutional_email" field.
func InstitutionalEmailHasPrefix(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldHasPrefix(FieldInstitutionalEmail, v))
}

// InstitutionalEmailHasSuffix applies the HasSuffix predicate on the "institutional_email" field.
func InstitutionalEmailHasSuffix(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldHasSuffix(FieldInstitutionalEmail, v))
}

// InstitutionalEmailEqualFold applies the EqualFold predicate on the "institutional_email" field.
func InstitutionalEmailEqualFold(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldEqualFold(FieldInstitutionalEmail, v))
}

// InstitutionalEmailContainsFold applies the ContainsFold predicate on the "institutional_email" field.
func InstitutionalEmailContainsFold(v string) predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldContainsFold(FieldInstitutionalEmail, v))
}

// PoliciesIsNil applies the IsNil predicate on the "policies" field.
func PoliciesIsNil() predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldIsNull(FieldPolicies))
}

// PoliciesNotNil applies the NotNil predicate on the "policies" field.
func PoliciesNotNil() predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldNotNull(FieldPolicies))
}

// FeatureFlagsIsNil applies the IsNil predicate on the "feature_flags" field.
func FeatureFlagsIsNil() predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldIsNull(FieldFeatureFlags))
}

// FeatureFlagsNotNil applies the NotNil predicate on the "feature_flags" field.
func FeatureFlagsNotNil() predicate.TenantSettings {
	return predicate.TenantSettings(sql.FieldNotNull(FieldFeatureFlags))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.TenantSettings {
	return predicate.TenantSettings(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenants) predicate.TenantSettings {
	return predicate.TenantSettings(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TenantSettings) predicate.TenantSettings {
	return predicate.TenantSettings(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TenantSettings) predicate.TenantSettings {
	return predicate.TenantSettings(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TenantSettings) predicate.TenantSettings {
	return predicate.TenantSettings(sql.NotPredicates(p))
}
