// Code generated by ent, DO NOT EDIT.

package activities

import (
	"hexagonal-go-backend/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Activities {
	return predicate.Activities(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Activities {
	return predicate.Activities(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Activities {
	return predicate.Activities(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Activities {
	return predicate.Activities(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Activities {
	return predicate.Activities(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Activities {
	return predicate.Activities(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Activities {
	return predicate.Activities(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Activities {
	return predicate.Activities(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Activities {
	return predicate.Activities(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Activities {
	return predicate.Activities(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Activities {
	return predicate.Activities(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Activities {
	return predicate.Activities(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Activities {
	return predicate.Activities(sql.FieldEQ(FieldUpdatedAt, v))
}

// LessonID applies equality check predicate on the "lesson_id" field. It's identical to LessonIDEQ.
func LessonID(v string) predicate.Activities {
	return predicate.Activities(sql.FieldEQ(FieldLessonID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Activities {
	return predicate.Activities(sql.FieldEQ(FieldTitle, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Activities {
	return predicate.Activities(sql.FieldEQ(FieldType, v))
}

// IsRequired applies equality check predicate on the "is_required" field. It's identical to IsRequiredEQ.
func IsRequired(v bool) predicate.Activities {
	return predicate.Activities(sql.FieldEQ(FieldIsRequired, v))
}

// SequenceOrder applies equality check predicate on the "sequence_order" field. It's identical to SequenceOrderEQ.
func SequenceOrder(v int) predicate.Activities {
	return predicate.Activities(sql.FieldEQ(FieldSequenceOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Activities {
	return predicate.Activities(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Activities {
	return predicate.Activities(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Activities {
	return predicate.Activities(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Activities {
	return predicate.Activities(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Activities {
	return predicate.Activities(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Activities {
	return predicate.Activities(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Activities {
	return predicate.Activities(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Activities {
	return predicate.Activities(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Activities {
	return predicate.Activities(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Activities {
	return predicate.Activities(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Activities {
	return predicate.Activities(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Activities {
	return predicate.Activities(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Activities {
	return predicate.Activities(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Activities {
	return predicate.Activities(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Activities {
	return predicate.Activities(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Activities {
	return predicate.Activities(sql.FieldLTE(FieldUpdatedAt, v))
}

// LessonIDEQ applies the EQ predicate on the "lesson_id" field.
func LessonIDEQ(v string) predicate.Activities {
	return predicate.Activities(sql.FieldEQ(FieldLessonID, v))
}

// LessonIDNEQ applies the NEQ predicate on the "lesson_id" field.
func LessonIDNEQ(v string) predicate.Activities {
	return predicate.Activities(sql.FieldNEQ(FieldLessonID, v))
}

// LessonIDIn applies the In predicate on the "lesson_id" field.
func LessonIDIn(vs ...string) predicate.Activities {
	return predicate.Activities(sql.FieldIn(FieldLessonID, vs...))
}

// LessonIDNotIn applies the NotIn predicate on the "lesson_id" field.
func LessonIDNotIn(vs ...string) predicate.Activities {
	return predicate.Activities(sql.FieldNotIn(FieldLessonID, vs...))
}

// LessonIDGT applies the GT predicate on the "lesson_id" field.
func LessonIDGT(v string) predicate.Activities {
	return predicate.Activities(sql.FieldGT(FieldLessonID, v))
}

// LessonIDGTE applies the GTE predicate on the "lesson_id" field.
func LessonIDGTE(v string) predicate.Activities {
	return predicate.Activities(sql.FieldGTE(FieldLessonID, v))
}

// LessonIDLT applies the LT predicate on the "lesson_id" field.
func LessonIDLT(v string) predicate.Activities {
	return predicate.Activities(sql.FieldLT(FieldLessonID, v))
}

// LessonIDLTE applies the LTE predicate on the "lesson_id" field.
func LessonIDLTE(v string) predicate.Activities {
	return predicate.Activities(sql.FieldLTE(FieldLessonID, v))
}

// LessonIDContains applies the Contains predicate on the "lesson_id" field.
func LessonIDContains(v string) predicate.Activities {
	return predicate.Activities(sql.FieldContains(FieldLessonID, v))
}

// LessonIDHasPrefix applies the HasPrefix predicate on the "lesson_id" field.
func LessonIDHasPrefix(v string) predicate.Activities {
	return predicate.Activities(sql.FieldHasPrefix(FieldLessonID, v))
}

// LessonIDHasSuffix applies the HasSuffix predicate on the "lesson_id" field.
func LessonIDHasSuffix(v string) predicate.Activities {
	return predicate.Activities(sql.FieldHasSuffix(FieldLessonID, v))
}

// LessonIDEqualFold applies the EqualFold predicate on the "lesson_id" field.
func LessonIDEqualFold(v string) predicate.Activities {
	return predicate.Activities(sql.FieldEqualFold(FieldLessonID, v))
}

// LessonIDContainsFold applies the ContainsFold predicate on the "lesson_id" field.
func LessonIDContainsFold(v string) predicate.Activities {
	return predicate.Activities(sql.FieldContainsFold(FieldLessonID, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Activities {
	return predicate.Activities(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Activities {
	return predicate.Activities(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Activities {
	return predicate.Activities(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Activities {
	return predicate.Activities(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Activities {
	return predicate.Activities(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Activities {
	return predicate.Activities(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Activities {
	return predicate.Activities(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Activities {
	return predicate.Activities(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Activities {
	return predicate.Activities(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Activities {
	return predicate.Activities(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Activities {
	return predicate.Activities(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Activities {
	return predicate.Activities(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Activities {
	return predicate.Activities(sql.FieldContainsFold(FieldTitle, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Activities {
	return predicate.Activities(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Activities {
	return predicate.Activities(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Activities {
	return predicate.Activities(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Activities {
	return predicate.Activities(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Activities {
	return predicate.Activities(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Activities {
	return predicate.Activities(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Activities {
	return predicate.Activities(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Activities {
	return predicate.Activities(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Activities {
	return predicate.Activities(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Activities {
	return predicate.Activities(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Activities {
	return predicate.Activities(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Activities {
	return predicate.Activities(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Activities {
	return predicate.Activities(sql.FieldContainsFold(FieldType, v))
}

// IsRequiredEQ applies the EQ predicate on the "is_required" field.
func IsRequiredEQ(v bool) predicate.Activities {
	return predicate.Activities(sql.FieldEQ(FieldIsRequired, v))
}

// IsRequiredNEQ applies the NEQ predicate on the "is_required" field.
func IsRequiredNEQ(v bool) predicate.Activities {
	return predicate.Activities(sql.FieldNEQ(FieldIsRequired, v))
}

// SequenceOrderEQ applies the EQ predicate on the "sequence_order" field.
func SequenceOrderEQ(v int) predicate.Activities {
	return predicate.Activities(sql.FieldEQ(FieldSequenceOrder, v))
}

// SequenceOrderNEQ applies the NEQ predicate on the "sequence_order" field.
func SequenceOrderNEQ(v int) predicate.Activities {
	return predicate.Activities(sql.FieldNEQ(FieldSequenceOrder, v))
}

// SequenceOrderIn applies the In predicate on the "sequence_order" field.
func SequenceOrderIn(vs ...int) predicate.Activities {
	return predicate.Activities(sql.FieldIn(FieldSequenceOrder, vs...))
}

// SequenceOrderNotIn applies the NotIn predicate on the "sequence_order" field.
func SequenceOrderNotIn(vs ...int) predicate.Activities {
	return predicate.Activities(sql.FieldNotIn(FieldSequenceOrder, vs...))
}

// SequenceOrderGT applies the GT predicate on the "sequence_order" field.
func SequenceOrderGT(v int) predicate.Activities {
	return predicate.Activities(sql.FieldGT(FieldSequenceOrder, v))
}

// SequenceOrderGTE applies the GTE predicate on the "sequence_order" field.
func SequenceOrderGTE(v int) predicate.Activities {
	return predicate.Activities(sql.FieldGTE(FieldSequenceOrder, v))
}

// SequenceOrderLT applies the LT predicate on the "sequence_order" field.
func SequenceOrderLT(v int) predicate.Activities {
	return predicate.Activities(sql.FieldLT(FieldSequenceOrder, v))
}

// SequenceOrderLTE applies the LTE predicate on the "sequence_order" field.
func SequenceOrderLTE(v int) predicate.Activities {
	return predicate.Activities(sql.FieldLTE(FieldSequenceOrder, v))
}

// HasLesson applies the HasEdge predicate on the "lesson" edge.
func HasLesson() predicate.Activities {
	return predicate.Activities(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LessonTable, LessonColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLessonWith applies the HasEdge predicate on the "lesson" edge with a given conditions (other predicates).
func HasLessonWith(preds ...predicate.Lessons) predicate.Activities {
	return predicate.Activities(func(s *sql.Selector) {
		step := newLessonStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasResources applies the HasEdge predicate on the "resources" edge.
func HasResources() predicate.Activities {
	return predicate.Activities(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ResourcesTable, ResourcesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasResourcesWith applies the HasEdge predicate on the "resources" edge with a given conditions (other predicates).
func HasResourcesWith(preds ...predicate.CourseResources) predicate.Activities {
	return predicate.Activities(func(s *sql.Selector) {
		step := newResourcesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Activities) predicate.Activities {
	return predicate.Activities(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Activities) predicate.Activities {
	return predicate.Activities(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Activities) predicate.Activities {
	return predicate.Activities(sql.NotPredicates(p))
}
