// Code generated by ent, DO NOT EDIT.

package intercept

import (
	"context"
	"fmt"

	"hexagonal-go-backend/internal/ent"
	"hexagonal-go-backend/internal/ent/activities"
	"hexagonal-go-backend/internal/ent/coursecategories"
	"hexagonal-go-backend/internal/ent/coursemodules"
	"hexagonal-go-backend/internal/ent/courseresources"
	"hexagonal-go-backend/internal/ent/coursetemplates"
	"hexagonal-go-backend/internal/ent/courseversions"
	"hexagonal-go-backend/internal/ent/lessons"
	"hexagonal-go-backend/internal/ent/predicate"
	"hexagonal-go-backend/internal/ent/syllabi"
	"hexagonal-go-backend/internal/ent/user"

	"entgo.io/ent/dialect/sql"
)

// The Query interface represents an operation that queries a graph.
// By using this interface, users can write generic code that manipulates
// query builders of different types.
type Query interface {
	// Type returns the string representation of the query type.
	Type() string
	// Limit the number of records to be returned by this query.
	Limit(int)
	// Offset to start from.
	Offset(int)
	// Unique configures the query builder to filter duplicate records.
	Unique(bool)
	// Order specifies how the records should be ordered.
	Order(...func(*sql.Selector))
	// WhereP appends storage-level predicates to the query builder. Using this method, users
	// can use type-assertion to append predicates that do not depend on any generated package.
	WhereP(...func(*sql.Selector))
}

// The Func type is an adapter that allows ordinary functions to be used as interceptors.
// Unlike traversal functions, interceptors are skipped during graph traversals. Note that the
// implementation of Func is different from the one defined in entgo.io/ent.InterceptFunc.
type Func func(context.Context, Query) error

// Intercept calls f(ctx, q) and then applied the next Querier.
func (f Func) Intercept(next ent.Querier) ent.Querier {
	return ent.QuerierFunc(func(ctx context.Context, q ent.Query) (ent.Value, error) {
		query, err := NewQuery(q)
		if err != nil {
			return nil, err
		}
		if err := f(ctx, query); err != nil {
			return nil, err
		}
		return next.Query(ctx, q)
	})
}

// The TraverseFunc type is an adapter to allow the use of ordinary function as Traverser.
// If f is a function with the appropriate signature, TraverseFunc(f) is a Traverser that calls f.
type TraverseFunc func(context.Context, Query) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFunc) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFunc) Traverse(ctx context.Context, q ent.Query) error {
	query, err := NewQuery(q)
	if err != nil {
		return err
	}
	return f(ctx, query)
}

// The ActivitiesFunc type is an adapter to allow the use of ordinary function as a Querier.
type ActivitiesFunc func(context.Context, *ent.ActivitiesQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ActivitiesFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ActivitiesQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ActivitiesQuery", q)
}

// The TraverseActivities type is an adapter to allow the use of ordinary function as Traverser.
type TraverseActivities func(context.Context, *ent.ActivitiesQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseActivities) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseActivities) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ActivitiesQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ActivitiesQuery", q)
}

// The CourseCategoriesFunc type is an adapter to allow the use of ordinary function as a Querier.
type CourseCategoriesFunc func(context.Context, *ent.CourseCategoriesQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f CourseCategoriesFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.CourseCategoriesQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.CourseCategoriesQuery", q)
}

// The TraverseCourseCategories type is an adapter to allow the use of ordinary function as Traverser.
type TraverseCourseCategories func(context.Context, *ent.CourseCategoriesQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseCourseCategories) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseCourseCategories) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.CourseCategoriesQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.CourseCategoriesQuery", q)
}

// The CourseModulesFunc type is an adapter to allow the use of ordinary function as a Querier.
type CourseModulesFunc func(context.Context, *ent.CourseModulesQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f CourseModulesFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.CourseModulesQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.CourseModulesQuery", q)
}

// The TraverseCourseModules type is an adapter to allow the use of ordinary function as Traverser.
type TraverseCourseModules func(context.Context, *ent.CourseModulesQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseCourseModules) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseCourseModules) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.CourseModulesQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.CourseModulesQuery", q)
}

// The CourseResourcesFunc type is an adapter to allow the use of ordinary function as a Querier.
type CourseResourcesFunc func(context.Context, *ent.CourseResourcesQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f CourseResourcesFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.CourseResourcesQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.CourseResourcesQuery", q)
}

// The TraverseCourseResources type is an adapter to allow the use of ordinary function as Traverser.
type TraverseCourseResources func(context.Context, *ent.CourseResourcesQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseCourseResources) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseCourseResources) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.CourseResourcesQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.CourseResourcesQuery", q)
}

// The CourseTemplatesFunc type is an adapter to allow the use of ordinary function as a Querier.
type CourseTemplatesFunc func(context.Context, *ent.CourseTemplatesQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f CourseTemplatesFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.CourseTemplatesQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.CourseTemplatesQuery", q)
}

// The TraverseCourseTemplates type is an adapter to allow the use of ordinary function as Traverser.
type TraverseCourseTemplates func(context.Context, *ent.CourseTemplatesQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseCourseTemplates) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseCourseTemplates) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.CourseTemplatesQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.CourseTemplatesQuery", q)
}

// The CourseVersionsFunc type is an adapter to allow the use of ordinary function as a Querier.
type CourseVersionsFunc func(context.Context, *ent.CourseVersionsQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f CourseVersionsFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.CourseVersionsQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.CourseVersionsQuery", q)
}

// The TraverseCourseVersions type is an adapter to allow the use of ordinary function as Traverser.
type TraverseCourseVersions func(context.Context, *ent.CourseVersionsQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseCourseVersions) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseCourseVersions) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.CourseVersionsQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.CourseVersionsQuery", q)
}

// The LessonsFunc type is an adapter to allow the use of ordinary function as a Querier.
type LessonsFunc func(context.Context, *ent.LessonsQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f LessonsFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.LessonsQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.LessonsQuery", q)
}

// The TraverseLessons type is an adapter to allow the use of ordinary function as Traverser.
type TraverseLessons func(context.Context, *ent.LessonsQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseLessons) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseLessons) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.LessonsQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.LessonsQuery", q)
}

// The SyllabiFunc type is an adapter to allow the use of ordinary function as a Querier.
type SyllabiFunc func(context.Context, *ent.SyllabiQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SyllabiFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SyllabiQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SyllabiQuery", q)
}

// The TraverseSyllabi type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSyllabi func(context.Context, *ent.SyllabiQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSyllabi) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSyllabi) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SyllabiQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SyllabiQuery", q)
}

// The UserFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserFunc func(context.Context, *ent.UserQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UserFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UserQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UserQuery", q)
}

// The TraverseUser type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUser func(context.Context, *ent.UserQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUser) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUser) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UserQuery", q)
}

// NewQuery returns the generic Query interface for the given typed query.
func NewQuery(q ent.Query) (Query, error) {
	switch q := q.(type) {
	case *ent.ActivitiesQuery:
		return &query[*ent.ActivitiesQuery, predicate.Activities, activities.OrderOption]{typ: ent.TypeActivities, tq: q}, nil
	case *ent.CourseCategoriesQuery:
		return &query[*ent.CourseCategoriesQuery, predicate.CourseCategories, coursecategories.OrderOption]{typ: ent.TypeCourseCategories, tq: q}, nil
	case *ent.CourseModulesQuery:
		return &query[*ent.CourseModulesQuery, predicate.CourseModules, coursemodules.OrderOption]{typ: ent.TypeCourseModules, tq: q}, nil
	case *ent.CourseResourcesQuery:
		return &query[*ent.CourseResourcesQuery, predicate.CourseResources, courseresources.OrderOption]{typ: ent.TypeCourseResources, tq: q}, nil
	case *ent.CourseTemplatesQuery:
		return &query[*ent.CourseTemplatesQuery, predicate.CourseTemplates, coursetemplates.OrderOption]{typ: ent.TypeCourseTemplates, tq: q}, nil
	case *ent.CourseVersionsQuery:
		return &query[*ent.CourseVersionsQuery, predicate.CourseVersions, courseversions.OrderOption]{typ: ent.TypeCourseVersions, tq: q}, nil
	case *ent.LessonsQuery:
		return &query[*ent.LessonsQuery, predicate.Lessons, lessons.OrderOption]{typ: ent.TypeLessons, tq: q}, nil
	case *ent.SyllabiQuery:
		return &query[*ent.SyllabiQuery, predicate.Syllabi, syllabi.OrderOption]{typ: ent.TypeSyllabi, tq: q}, nil
	case *ent.UserQuery:
		return &query[*ent.UserQuery, predicate.User, user.OrderOption]{typ: ent.TypeUser, tq: q}, nil
	default:
		return nil, fmt.Errorf("unknown query type %T", q)
	}
}

type query[T any, P ~func(*sql.Selector), R ~func(*sql.Selector)] struct {
	typ string
	tq  interface {
		Limit(int) T
		Offset(int) T
		Unique(bool) T
		Order(...R) T
		Where(...P) T
	}
}

func (q query[T, P, R]) Type() string {
	return q.typ
}

func (q query[T, P, R]) Limit(limit int) {
	q.tq.Limit(limit)
}

func (q query[T, P, R]) Offset(offset int) {
	q.tq.Offset(offset)
}

func (q query[T, P, R]) Unique(unique bool) {
	q.tq.Unique(unique)
}

func (q query[T, P, R]) Order(orders ...func(*sql.Selector)) {
	rs := make([]R, len(orders))
	for i := range orders {
		rs[i] = orders[i]
	}
	q.tq.Order(rs...)
}

func (q query[T, P, R]) WhereP(ps ...func(*sql.Selector)) {
	p := make([]P, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	q.tq.Where(p...)
}
