// Code generated by ent, DO NOT EDIT.

package privacy

import (
	"context"

	"hexagonal-go-backend/internal/ent"

	"entgo.io/ent/privacy"
)

var (
	// Allow may be returned by rules to indicate that the policy
	// evaluation should terminate with allow decision.
	Allow = privacy.Allow

	// Deny may be returned by rules to indicate that the policy
	// evaluation should terminate with deny decision.
	Deny = privacy.Deny

	// Skip may be returned by rules to indicate that the policy
	// evaluation should continue to the next rule.
	Skip = privacy.Skip
)

// Allowf returns a formatted wrapped Allow decision.
func Allowf(format string, a ...any) error {
	return privacy.Allowf(format, a...)
}

// Denyf returns a formatted wrapped Deny decision.
func Denyf(format string, a ...any) error {
	return privacy.Denyf(format, a...)
}

// Skipf returns a formatted wrapped Skip decision.
func Skipf(format string, a ...any) error {
	return privacy.Skipf(format, a...)
}

// DecisionContext creates a new context from the given parent context with
// a policy decision attach to it.
func DecisionContext(parent context.Context, decision error) context.Context {
	return privacy.DecisionContext(parent, decision)
}

// DecisionFromContext retrieves the policy decision from the context.
func DecisionFromContext(ctx context.Context) (error, bool) {
	return privacy.DecisionFromContext(ctx)
}

type (
	// Policy groups query and mutation policies.
	Policy = privacy.Policy

	// QueryRule defines the interface deciding whether a
	// query is allowed and optionally modify it.
	QueryRule = privacy.QueryRule
	// QueryPolicy combines multiple query rules into a single policy.
	QueryPolicy = privacy.QueryPolicy

	// MutationRule defines the interface which decides whether a
	// mutation is allowed and optionally modifies it.
	MutationRule = privacy.MutationRule
	// MutationPolicy combines multiple mutation rules into a single policy.
	MutationPolicy = privacy.MutationPolicy
	// MutationRuleFunc type is an adapter which allows the use of
	// ordinary functions as mutation rules.
	MutationRuleFunc = privacy.MutationRuleFunc

	// QueryMutationRule is an interface which groups query and mutation rules.
	QueryMutationRule = privacy.QueryMutationRule
)

// QueryRuleFunc type is an adapter to allow the use of
// ordinary functions as query rules.
type QueryRuleFunc func(context.Context, ent.Query) error

// Eval returns f(ctx, q).
func (f QueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	return f(ctx, q)
}

// AlwaysAllowRule returns a rule that returns an allow decision.
func AlwaysAllowRule() QueryMutationRule {
	return privacy.AlwaysAllowRule()
}

// AlwaysDenyRule returns a rule that returns a deny decision.
func AlwaysDenyRule() QueryMutationRule {
	return privacy.AlwaysDenyRule()
}

// ContextQueryMutationRule creates a query/mutation rule from a context eval func.
func ContextQueryMutationRule(eval func(context.Context) error) QueryMutationRule {
	return privacy.ContextQueryMutationRule(eval)
}

// OnMutationOperation evaluates the given rule only on a given mutation operation.
func OnMutationOperation(rule MutationRule, op ent.Op) MutationRule {
	return privacy.OnMutationOperation(rule, op)
}

// DenyMutationOperationRule returns a rule denying specified mutation operation.
func DenyMutationOperationRule(op ent.Op) MutationRule {
	rule := MutationRuleFunc(func(_ context.Context, m ent.Mutation) error {
		return Denyf("ent/privacy: operation %s is not allowed", m.Op())
	})
	return OnMutationOperation(rule, op)
}

// The CourseCategoriesQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type CourseCategoriesQueryRuleFunc func(context.Context, *ent.CourseCategoriesQuery) error

// EvalQuery return f(ctx, q).
func (f CourseCategoriesQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.CourseCategoriesQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.CourseCategoriesQuery", q)
}

// The CourseCategoriesMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type CourseCategoriesMutationRuleFunc func(context.Context, *ent.CourseCategoriesMutation) error

// EvalMutation calls f(ctx, m).
func (f CourseCategoriesMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.CourseCategoriesMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.CourseCategoriesMutation", m)
}

// The CourseModulesQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type CourseModulesQueryRuleFunc func(context.Context, *ent.CourseModulesQuery) error

// EvalQuery return f(ctx, q).
func (f CourseModulesQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.CourseModulesQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.CourseModulesQuery", q)
}

// The CourseModulesMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type CourseModulesMutationRuleFunc func(context.Context, *ent.CourseModulesMutation) error

// EvalMutation calls f(ctx, m).
func (f CourseModulesMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.CourseModulesMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.CourseModulesMutation", m)
}

// The CourseTemplatesQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type CourseTemplatesQueryRuleFunc func(context.Context, *ent.CourseTemplatesQuery) error

// EvalQuery return f(ctx, q).
func (f CourseTemplatesQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.CourseTemplatesQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.CourseTemplatesQuery", q)
}

// The CourseTemplatesMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type CourseTemplatesMutationRuleFunc func(context.Context, *ent.CourseTemplatesMutation) error

// EvalMutation calls f(ctx, m).
func (f CourseTemplatesMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.CourseTemplatesMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.CourseTemplatesMutation", m)
}

// The CourseVersionsQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type CourseVersionsQueryRuleFunc func(context.Context, *ent.CourseVersionsQuery) error

// EvalQuery return f(ctx, q).
func (f CourseVersionsQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.CourseVersionsQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.CourseVersionsQuery", q)
}

// The CourseVersionsMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type CourseVersionsMutationRuleFunc func(context.Context, *ent.CourseVersionsMutation) error

// EvalMutation calls f(ctx, m).
func (f CourseVersionsMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.CourseVersionsMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.CourseVersionsMutation", m)
}

// The SyllabiQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type SyllabiQueryRuleFunc func(context.Context, *ent.SyllabiQuery) error

// EvalQuery return f(ctx, q).
func (f SyllabiQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SyllabiQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.SyllabiQuery", q)
}

// The SyllabiMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type SyllabiMutationRuleFunc func(context.Context, *ent.SyllabiMutation) error

// EvalMutation calls f(ctx, m).
func (f SyllabiMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.SyllabiMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.SyllabiMutation", m)
}

// The TenantSettingsQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type TenantSettingsQueryRuleFunc func(context.Context, *ent.TenantSettingsQuery) error

// EvalQuery return f(ctx, q).
func (f TenantSettingsQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.TenantSettingsQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.TenantSettingsQuery", q)
}

// The TenantSettingsMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type TenantSettingsMutationRuleFunc func(context.Context, *ent.TenantSettingsMutation) error

// EvalMutation calls f(ctx, m).
func (f TenantSettingsMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.TenantSettingsMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.TenantSettingsMutation", m)
}

// The TenantsQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type TenantsQueryRuleFunc func(context.Context, *ent.TenantsQuery) error

// EvalQuery return f(ctx, q).
func (f TenantsQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.TenantsQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.TenantsQuery", q)
}

// The TenantsMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type TenantsMutationRuleFunc func(context.Context, *ent.TenantsMutation) error

// EvalMutation calls f(ctx, m).
func (f TenantsMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.TenantsMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.TenantsMutation", m)
}

// The UserQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type UserQueryRuleFunc func(context.Context, *ent.UserQuery) error

// EvalQuery return f(ctx, q).
func (f UserQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.UserQuery", q)
}

// The UserMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type UserMutationRuleFunc func(context.Context, *ent.UserMutation) error

// EvalMutation calls f(ctx, m).
func (f UserMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.UserMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.UserMutation", m)
}
