// Code generated by ent, DO NOT EDIT.

package coursemodules

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the coursemodules type in the database.
	Label = "course_modules"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the coursemodules in the database.
	Table = "course_modules"
)

// Columns holds all SQL columns for coursemodules fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the CourseModules queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}
